### ISSUE TITLE
Tye missconfiguring dapr sidecars?

### ISSUE THREAD

**Issue by mmisztal1980** [dotnet/tye#1000]
### Describe the bug
The dapr services appear to be miss-configured

### To Reproduce

- `tye run`
- Navigate to the tye dashboard
- Inspect the sidecar logs
- Observe the following error:

```
[pubsub-service-dapr_e2c112e1-e]: time="2021-04-02T16:50:17.860404+02:00" level=debug msg="try to connect to placement service: localhost:57810:6050" app_id=pubsub-service instance=DESKTOP-IINRD72 scope=dapr.runtime.actor.internal.placement type=log ver=1.1.0
[pubsub-service-dapr_e2c112e1-e]: time="2021-04-02T16:50:17.860404+02:00" level=debug msg="error connecting to placement service: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: address localhost:57810:6050: too many colons in address\"" app_id=pubsub-service instance=DESKTOP-IINRD72 scope=dapr.runtime.actor.internal.placement type=log ver=1.1.0
```

The error is most likely referring to: `localhost:57810:6050` which doesn't appear right.

The service appears to be started with correct cmdline invocation:

`C:/dapr/dapr.exe run --app-id pubsub-service1 --app-port 15000 --dapr-grpc-port 52199 --dapr-http-port 52200 --metrics-port 52201 --placement-host-address localhost:52194 --log-level debug --components-path ./components`

If you tell me where to look I can try to have it fixed.

### Further technical details

- Include the output of `tye --version` : `0.7.0-alpha.21176.1+3756e2a60e1e64492ac8e9749ce5a0cdc1744878`
- The platform (Linux/macOS/Windows) : Windows

cc: @rynowak @jkotalik

**Comment by jkotalik** [comment]
Yeah that seems like a new bug. Not sure where two ports are being appended. I'll look into it.

**Comment by jkotalik** [comment]
Also, what sample are you running? Would like to see the tye.yaml that causes this.

**Comment by Yitzchok** [comment]
I see the same errors in the logs.

It seems like the issue stems from 

`		args = append(args, fmt.Sprintf("%s:6050", placementHost))`
https://github.com/dapr/cli/blob/7c1c2c239cfc91332a43d30ebc811cb1845cdbd5/pkg/standalone/run.go#L103

**Comment by jkotalik** [comment]
@Yitzchok that seems right, I went ahead and filed an issue in the cli repo: https://github.com/dapr/cli/issues/705
