### ISSUE TITLE
Tye CLI not accessible in Terminal on M1 macOS

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/tye#1035]
I install the latest CI-build of Tye on an M1 Mac, but when entering the command it cannot be found.

When running ```./tye```from the ```~/.dotnet/tools```directory it works.

It seem it has been added to the ```$PATH``` It seems like ~ does not expand. (https://github.com/dotnet/sdk/issues/9415)

I have reinstalled the tools but no luck.

````
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
````

```
robert@Roberts-MBP-2 tools % dotnet --list-sdks
3.0.103 [/usr/local/share/dotnet/sdk]
3.1.408 [/usr/local/share/dotnet/sdk]
5.0.202 [/usr/local/share/dotnet/sdk]
```

```
robert@Roberts-MBP-2 tools % ls -la
total 520
drwxr-xr-x   5 robert  staff     160 May  6 09:12 .
drwxr-xr-x  19 robert  staff     608 May  5 15:06 ..
drwxr-xr-x   5 robert  staff     160 May  6 09:12 .store
-rwxr--r--   1 robert  staff  165976 Feb 11 18:44 dotnet-format
-rwxr-xr-x   1 robert  staff   95244 May  6 09:12 tye
```

**Comment by robertsundstrom** [comment]
My workaround it to put this in ```~/.zshrc```: 

```
export PATH=$HOME/.dotnet/tools:$PATH
```

**Comment by jkotalik** [comment]
@philliphoff did you see this when you were using tye on your M1?

**Comment by philliphoff** [comment]
To be honest, I don't recall.  That said, I *do* have this in my `.zprofile`:

```bash
# Add Tye to PATH.
export PATH="$PATH:/Users/<user>/.dotnet/tools"
```

I have to imagine that I added it myself, given the other items/comments in the file.  Anyway, I know I've had trouble in the past with using `~/` as part of paths in `PATH`.  Looking at my `PATH`, I see both `~/.dotnet/tools` as well as the path I added via my `.zprofile`.  I'm not sure where `~/.dotnet/tools` came from; I don't see another shell configuration file with that anywhere.

**Comment by philliphoff** [comment]
Closing this as it's not an issue specific to Tye, though I did add a note to the installation guide that the modification to `PATH` may be needed.
