### ISSUE TITLE
Where does the name "Tye" come from?

### ISSUE THREAD

**Issue by FeynmanFan** [dotnet/tye#1045]
I'm seeing definitions of a small box, a pasture, or a piece of rigging in a naval context. What's the right metaphor here?

**Comment by jongio** [comment]
tye
A chain or rope used for hoisting or lowering a yard. A tye runs from the horizontal center of a given yard to a corresponding mast and from there down to a tackle. Sometimes more specifically called a chain tye or a rope tye.[75]

https://en.wikipedia.org/wiki/Glossary_of_nautical_terms

**Comment by FeynmanFan** [comment]
That's what I figured - thanks.
