### ISSUE TITLE
Tye should throw when multiple bindings are specified without names

### ISSUE THREAD

**Issue by jkotalik** [dotnet/tye#106]

**Comment by davidfowl** [comment]
We have a place to do this type of model validation now https://github.com/dotnet/tye/blob/944027b30cc4039c7e025932dafea601af0a6267/src/Microsoft.Tye.Core/ApplicationFactory.cs#L190

**Comment by davidfowl** [comment]
Is help wanted our up for grabs @rynowak ?

**Comment by jkotalik** [comment]
This is done.
