### ISSUE TITLE
Tye fails to run project when SDK 6.0 preview 4 installed

### ISSUE THREAD

**Issue by martinstenhoff** [dotnet/tye#1066]
After I installed preview4 of the new dotnet sdk 6.0 my tye project fails to run

```
Loading Application Details...
Restoring and evaluating projects
Evaluating project failed with exit code 1
Output: C:\Users\MartinStenhoff\AppData\Local\Temp\ntvqhri1.4x4\byxys54o.xqe.proj : error MSB4057: The target "Restore" does not exist in the project.

Build FAILED.

C:\Users\MartinStenhoff\AppData\Local\Temp\ntvqhri1.4x4\byxys54o.xqe.proj : error MSB4057: The target "Restore" does not exist in the project.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.06

Error:
Restore and project evaluation took: 298,4885ms
Drats! 'run' failed:
        Evaluated project metadata file could not be found for service payment-frontend
```

I've seen a ticket about msbuild [(6373)](https://github.com/dotnet/msbuild/issues/6373) bundled in P4 having this issue, but isn't my global.json I have supposed to fix the sdk to the one defined in the file?

```
{
  "sdk": {
	  "version": "5.0.300"
  }
}
```

After I removed P4 tye works again.

**Comment by philliphoff** [comment]
0.7.0 (released today!) has some fixes specifically for .NET 6 Preview 4.  Give it a try and let us know whether that resolves your issue.

**Comment by martinstenhoff** [comment]
Yes, upgrading to Tye 0.7.0 solved my problem.
