### ISSUE TITLE
Version 0.8.0 of the nuget package is missing

### ISSUE THREAD

**Issue by rafaelldi** [dotnet/tye#1117]
Hello!
There was a new release a few days ago, but the latest version of the nuget package is still 0.7.0 ([nuget.org/Microsoft.Tye](https://www.nuget.org/packages/Microsoft.Tye/)). Did you forget to upload the new version, or did I miss something?
Thank you.

**Comment by philliphoff** [comment]
@pratiksanglikar Did the 0.8.0 release get un-hidden?

**Comment by pratiksanglikar** [comment]
@rafaelldi, thanks for bringing attention to this.
it's listed now.

**Comment by rafaelldi** [comment]
Great, thanks!
