### ISSUE TITLE
Is there a way to specify the dashboard port in tye.yaml?

### ISSUE THREAD

**Issue by daniel-simpson** [dotnet/tye#1158]
### What should we add or change to make your life better?

Adding a top level `port` element to the Tye schema, to allow setting the dashboard port (defaults to 8000) from the `tye.yaml` configuration file

### Why is this important to you?

We're using Tye extensively at my new workplace, and due to the inability to order the startup of each service (#652), we have three "levels" of tye.yaml files that need to be executed in a specific order:

- `dependencies/tye.yaml`
- `intermediate/tye.yaml`
- `services/tye,.yaml`

 In order to run three instances of Tye, I need to pass in a port (i.e. `tye run --port 8001`) so port conflicts don't occur during startup.  Would be very handy to be able to specify this port value in the tye.yaml rather than having to remember to pass a port value, e.g.

```yaml
name: dependencies
port: 8001

services:
  - myservice
  ...
```

**Comment by davidfowl** [comment]
Tye will use a random port if 8000 is in use. You'd only need this if you want a stable port. If we did this it would be called dashboardPort

**Comment by daniel-simpson** [comment]
I understand that it will use a random port if something is in use, but what I'm really after is the `services/tye.yaml` (the third yaml file I am running) to be the one on a "stable" port.

I need to run my dependencies first (`dependencies/tye.yaml`), so it ends up on port 8000, and then the configuration that I really care about / am using most (the last one, services.yaml) ends up on a random port.

Also, I'm happy to have a crack at implementing this if its something that other people would find useful :)

**Comment by daniel-simpson** [comment]
I've got some working code for this, but holding off on sending through a pull request until I get confirmation that this is something useful :) 

Let me know, happy to get some feedback!

**Comment by jonbdk** [comment]
I would second this as well.
Have two different projects, that I often run at the same time. 
And of course, I could just read it in the console when starting the seconds, but it would be nicer to just always know, project 1 was running on 8000 and project 2 on 8001.
Alternatively, use 8000 as default - if busy, use 8001, if busy, use 8002 (and so forth)

**Comment by davidfowl** [comment]
Wouldn't you rather have everything in a single dashboard though?

**Comment by daniel-simpson** [comment]
I absolutely would prefer a single dashboard!  Unfortunately I'm not able to move to that model as:

1. this is an existing set up, so I'm not able to make changes as freely as I would like
2. The lack of #652 means that I need to run prerequisite services first (databases, storage emulation, etc) in order for my services to come up without issues.  My team has chosen to work around this by separating order-of-operation layers into separate Tye files.

**Comment by philliphoff** [comment]
Closing per #1163.
