### ISSUE TITLE
Fail to install Tye CI build 0.11.0

### ISSUE THREAD

**Issue by v-ruizh** [dotnet/tye#1196]
**OS:** Windows 10

**Repro Steps:**
1. Install .NET Core 3.1.
2. Install  Tye CI build using [the command](https://github.com/dotnet/tye/blob/main/docs/getting_started.md#working-with-ci-builds).
`dotnet tool install -g Microsoft.Tye --version "0.11.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json`

**Expect:**
Succeed to install Tye CI build 0.11.0.

**Actual:**
Fail to install Tye CI build 0.11.0.
![image](https://user-images.githubusercontent.com/45614674/136640432-f43b5b99-a1e3-4392-a466-45f163c58a53.png)

**Error Info:**
```
C:\WINDOWS\system32>dotnet tool install -g Microsoft.Tye --version "0.11.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.413

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
error NU1102: Unable to find package microsoft.tye with version (>= 0.11.0)
error NU1102:   - Found 328 version(s) in https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json [ Nearest version: 0.10.0-alpha.21420.1 ]
error NU1102:   - Found 11 version(s) in nuget.org [ Nearest version: 0.10.0-alpha.21420.1 ]
The tool package could not be restored.
Tool 'microsoft.tye' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

```

**Comment by Hylaean** [comment]
Apparently there's a governance issue that blocks the build publishing

**Comment by Hylaean** [comment]
@philliphoff  There's a update-unsafe-components and failed steps in the build/publish process.

It hasn't been addressed for weeks now. I understand you may be busy with the release and but this makes the whole project look a bit dead.

**Comment by philliphoff** [comment]
@Hylaean I feel you, trust me. :-) While Tye is absolutely still under active development, it's admittedly slower than I'd like.  Our team has a number of responsibilities, not all of which are as publicly visible as projects like Tye, so not all of our efforts can be seen.

**Comment by Hylaean** [comment]
I have proposed https://github.com/dotnet/tye/pull/1218 to fix this.
A better solution would be to include this step in the PR validation gates
