### ISSUE TITLE
Is tye still approached as "experiement" for developers?

### ISSUE THREAD

**Issue by ardacetinkaya** [dotnet/tye#1199]
Maybe it is a silly one; but I want to learn that if "experiment at the moment" statement is still legit? If yes, what about the results of the experiment or if no, is there any solid roadmap?

In fact it is very clear in FAQ;

>"Put another way, Tye is a public incubation project from Microsoft. We're trying to build tools that help developers, and doing this with open source is the best way for us to try new ideas. We're looking to grow a community of early adopters who want to contribute and share ideas.
>
>Being an experiment also means that the future of what happens to Tye is not clear. Tye could live on as a product.. or the ideas could be folded in to other products."

But I want to learn if Tye is going to be approached as a product; maybe as build-in feature in Visual Studio. Any clear roadmap?

**Comment by BigMorty** [comment]
Thanks for your reply @ardacetinkaya.
