### ISSUE TITLE
Move Tye to .NET 6

### ISSUE THREAD

**Issue by philliphoff** [dotnet/tye#1213]
### What should we add or change to make your life better?

* Move Tye to .NET 6 now that it's GA.
* Consider moving to all-in-one executable released in both x86 and ARM flavors for each platform.
  * Consider then eliminating dependency on `dotnet tool` mechanism for installation (i.e. have Tye be a standalone CLI)

### Why is this important to you?

Developers will tend to migrate to .NET 6 being the new LTS version, meaning fewer will have .NET Core 3.x installed (currently required for Tye). Moving to .NET 6 will also avoid x86/arm issues currently seen on Apple Silicon.

If we were to also move to all-in-one executables, we could also eliminate the need for a particular version of .NET runtime just for the purposes of running Tye.  Eliminating our dependency on `dotnet tool` would also be helpful for those wishing to use Tye with non-.NET development platforms.

**Comment by Serge-N** [comment]
This essential, stilling having trouble running tye and native dotnet 6.

**Comment by philliphoff** [comment]
Notes re: single-file executables:

* There are uses of `Assembly.Location` which are apparently [not compatible](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#api-incompatibility) and would need refactoring.

**Comment by paulquinn** [comment]
The updated CI build instructions don't seem to work (at least for me " error NU1102: Unable to find package microsoft.tye with version (>= 0.11.0)") - has the 0.11 package been published?

Also, those instructions add a dotnet5 package source - should this be moved to dotnet6?

**Comment by philliphoff** [comment]
@paulquinn There were some corporate governance issues that blocked publishing CI builds to the CI feed.  These *should* be now resolved, but it may take some time and/or additional CI builds before they start showing up again.  As for the package source, while that sounds reasonable, I'll have to dig into the build infrastructure to see how it decides which feed Tye packages go into.

**Comment by cphillips83** [comment]
I would argue against removing the `dotnet tool` integration because its easy for a developer to do a `dotnet tool restore` instead of following a large CLI tool installation process. A dotnet tool manifest also helps enforce tool versioning.

**Comment by cphillips83** [comment]
@philliphoff Its still not available when using 

```
dotnet tool update -g Microsoft.Tye --version "0.11.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
```

**Comment by philliphoff** [comment]
@cphillips83 Like peeling an onion, resolving one set of corporate governance issues only served to expose another layer that contribute to our missing CI packages.  I'm still wading through those at the moment.
