### ISSUE TITLE
`dockerImage` should be just `image`

### ISSUE THREAD

**Issue by glennc** [dotnet/tye#122]
I don't want to leave it as `dockerImage` I am proposing we just call it image.

**Comment by ChadJessup** [comment]
I can't speak for @glennc - but, I believe  `dockerImage` as used in this repo, might often be referring to an OCI/rkt/docker image, or will soon as container tech is migrating (or has) to runc and containerd. I believe that the image format will also most likely be abstracted away by Kubernetes, when Tye is talking to k8s.

https://github.com/opencontainers/image-spec
https://www.opencontainers.org/faq
https://github.com/cri-o/cri-o
https://cri-o.io/ <- CNCF incubation to move K8s completely to OCI and related components.

`image` is also the standard key in a ton of yaml/json for these systems, and I believe 'dockerImage' will cause some 'cache misses' to users:

https://docs.docker.com/compose/compose-file/#image
https://github.com/helm/charts/search?q=image%3A&unscoped_q=image%3A

**Comment by larsw** [comment]
What @ChadJessup said - it should really not be tied to Docker at all.

**Comment by rynowak** [comment]
Sounds good. 😆  - just wanted to make sure we captured the rationale for changing something even though the issue was opened by the team member.
