### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by TheAngryByrd** [dotnet/tye#1248]
### What should we add or change to make your life better?

Release a new version

### Why is this important to you?

I'm unsure if https://github.com/dotnet/tye/issues/1145 would be fixed by [The move to net 6.0](https://github.com/dotnet/tye/commit/1c8577f98f4428117114fa1f287f1480b4b279ea) but it would be nice to try it out and see.

**Comment by fasteddys** [comment]
Target .net Core 6. 

Also add GUI option to run the same TYE development, making it easier to develop micro services quicker.

**Comment by fasteddys** [comment]
Hello @philliphoff the discovery and visual foot print of the microservices from a UI would be very helpful, i.e. beyond a yaml file.

Also - it would be nice to have a scaffolder that follows a consistent pattern to create new microservices, i.e. either inherit from a baseTyeMicroservice which has the options that can easily tye into the GUI, 

So for e.g. imagine the GUI for a RabbitMq or HangFireJobs. I use Hangfire template projects to build the serivces, but thier GUI also is able leverage the templates to watch /operate start stop those jobs - hope it makes sense to you. Sorry..

**Comment by philliphoff** [comment]
As 0.11.0 was released yesterday (finally!), I'm going to close this issue.
