### ISSUE TITLE
Undeploy not working

### ISSUE THREAD

**Issue by PerProjBackup** [dotnet/tye#1265]
0.10.0-alpha.21420.1+7cec0655cc474aee8d3c3a3d180678985209d439
Docker Engine v20.10.11    WSL 2
.NET 5 projects

I’ve successfully deployed my app to my Docker Desktop Kubernetes cluster using tye ‘build’, ‘push -i’ and ‘deploy -i’.

The k8s containers are running and I can browse to my WebApp.

When I try to undeploy, ‘tye undeploy’, I get:
Loading Application Details...
Drats! 'undeploy' failed:
        Unable connect to kubernetes.

Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
. . .

I’m following a Pluralsight course from 5/27/21 and they successfully use this command.

I could not find any documentation on the undeploy command.

Short of resetting my Kubernetes Cluster how do I undeploy?

Thank you.

**Work around:**
I created an _undeploy.ps1_ script:
kubectl delete deployment {name}
. . .
kubectl delete service {name}
. . .

**What did you use tye for?**
- [ ] Just taking the course at this point.

### What did you think of tye?
Great potential, I hope it gets released soon.

**Comment by umar-daraz-techverx** [comment]
same issue on my local

**Comment by omaranbari** [comment]
++ here using minkube, docker hub, and the tutorial

**Comment by ChuckBryan** [comment]
I am having a similar issue . If I run
```
tye undeploy -v Debug
```

the output includes:
----------------------------
Loading Application Details...
Restoring and evaluating projects
Resolved metadata for service frontend at D:\Projects\TyeBasicTutorial\frontend\obj\Debug\net6.0\MicrosoftTye.ProjectMetadata.txt
Resolved metadata for service backend at D:\Projects\TyeBasicTutorial\backend\obj\Debug\net6.0\MicrosoftTye.ProjectMetadata.txt
Restore and project evaluation took: 1231.3581ms
Found application version: 1.0.0
RunCommand=D:\Projects\TyeBasicTutorial\frontend\bin\Debug\net6.0\frontend.exe
RunArguments=
TargetPath=D:\Projects\TyeBasicTutorial\frontend\bin\Debug\net6.0\frontend.dll
PublishDir=bin\Debug\net6.0\publish\
AssemblyName=frontend
IntermediateOutputPath=obj\Debug\net6.0\
Found target framework: net6.0
Parsed target framework name: net
Parsed target framework version: 6.0
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 2.8629ms
Found application version: 1.0.0
RunCommand=D:\Projects\TyeBasicTutorial\backend\bin\Debug\net6.0\backend.exe
RunArguments=
TargetPath=D:\Projects\TyeBasicTutorial\backend\bin\Debug\net6.0\backend.dll
PublishDir=bin\Debug\net6.0\publish\
AssemblyName=backend
IntermediateOutputPath=obj\Debug\net6.0\
Found target framework: net6.0
Parsed target framework name: net
Parsed target framework version: 6.0
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 1.2639ms
Querying services
Found 2 matching services
Querying deployments
Found 2 matching deployments
Querying secrets
Found 0 matching secrets
Querying ingresses
Failed to query ingress.
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.ListNamespacedIngressWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Tye.UndeployHost.ExecuteUndeployAsync(OutputContext output, ApplicationBuilder application, String namespace, Boolean interactive, Boolean whatIf) in /_/src/tye/UndeployHost.cs:line 143

**Comment by philliphoff** [comment]
@PerProjBackup @umar-daraz-techverx @omaranbari @ChuckBryan I'm curious what version of Kubernetes (and Kubernetes tools) you're all using.  I'm not able to reproduce this on my M1 Mac, with the latest `k3d` or `minikube`.  I'm also not able to reproduce this on Windows with the latest `k3d`.  However, I *do* see the same error as @ChuckBryan when using `minikube` on Windows.

If I update to the [the latest (CI build)](https://github.com/dotnet/tye/blob/main/docs/getting_started.md#working-with-ci-builds) of Tye (0.11.*), then I can `undeploy` successfully with `minikube` on Windows.  Please try that and let me know if that resolves your issues as well.  (If I recall correctly, 0.10.0 used a very old version of the Kubernetes client library that was pulled forward as part of the effort to target .NET 6.  It may be that the old version of the library doesn't work against later versions of Kubernetes APIs.)

**Comment by omaranbari** [comment]
Docker version 20.10.12, build e91ed5707e
minikube version: v1.24.0
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

Running on linux

**Comment by ChuckBryan** [comment]
@philliphoff - I added my version of minikube and k8s in my original post. Upgrading to 0.11.0 of the Tye CLI worked in my case. I created the sample frontend/backend, deployed and then undeployed. 

Thank you for the guidance.

**Comment by philliphoff** [comment]
@PerProjBackup The 0.11.x version hasn't yet been released (so it's not in the standard feed), hence an unofficial CI build must be specifically installed.

@omaranbari Were you successful when updating to the 0.11.x build?

**Comment by PerProjBackup** [comment]
@philliphoff Is failing to delete the Ingress even though it said it did a known bug?

**Comment by philliphoff** [comment]
@PerProjBackup Can you show the `tye undeploy` output or a snippet that shows what's left on the cluster that shouldn't be?

I haven't seen any issues deleting the ingress instance, though I wouldn't expect Tye to uninstall the ingress controller itself, as that's typically something installed once per cluster and is independent of other deployed applications.  Tye tries to be helpful in deploying the ingress controller if none exists, but it has no way of knowing whether it's being used by other applications after that.

**Comment by PerProjBackup** [comment]
@philliphoff  I've reset my K8s cluster at this point.
I had added a ingress to the tye.yaml.
ingress:
- name: ingress
  bindings:
    - port: 8080
  rules:
    - path: /
      service: webapp1

When I ran 'tye deploy -i' it created all my services, deployments and the ingress (controller and pod for all).

When I ran 'tye undeploy' it said it deleted each one of the services and deployments. It also said it deleted the 'Ingress'.

It was not deleted, probably for the reasons you stated.

So the error, following your explanation, is not that it did not delete the ingress but that it reported it did.

I was not able to figure out how to delete the 'Ingress-nginx' manually, I had to reset the K8s cluster.  Do you know what kuberctl commands you would use to delete the 'ingress-nginx'?

**Comment by philliphoff** [comment]
@PerProjBackup I think there needs to be a distinction between the ingress controller (which provides the ingress infrastructure, which is deployed once per cluster) and ingress instances (which are created and associated with each application that makes use of ingress).  Tye creates ingress instances on `deploy`, and deletes them on `undeploy` (which is what it's reporting).  On `deploy`, Tye will also prompt to install the ingress controller if not already present on the cluster.  It will not, however, remove the ingress controller (because other applications may depend on it).

Tye installs the ingress controller by applying the [Kubernetes `ingress-nginx`](https://kubernetes.github.io/ingress-nginx/) configuration YAML.  Uninstalling is not a single-step operation, but involves deleting the ingress namespace, bindings, and CRDs.  I would defer to their documentation for installation and uninstallation details.

**Comment by omaranbari** [comment]
> @PerProjBackup The 0.11.x version hasn't yet been released (so it's not in the standard feed), hence an unofficial CI build must be specifically installed.
> 
> @omaranbari Were you successful when updating to the 0.11.x build?

The undeploy command ran successfully when I updated. However, I would think it should remove the repositories (frontend and backend) from DockerHub, but it doesn't. Is that expected behaviour?
Thank you

**Comment by philliphoff** [comment]
@omaranbari For the same reason Tye doesn't remove the ingress controller itself from the cluster, it does not remove published images from the repository as, once published, Tye has no way of knowing whether that same images is used elsewhere.

**Comment by omaranbari** [comment]
Thank you @philliphoff 
All is well then! I think this can be closed.
