### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by stephanjohnson** [dotnet/tye#1267]
There have been no new releases in months with very little activity from any of the core team.

Two years ago there was the ever present knowledge that the project *will* end in November 2020 as it is only an experiment. The warning has since been removed https://github.com/dotnet/tye/commit/65906ab7c6b88504388e0f28ac78f66a8485465f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5, or at least the *end times* part of it has been removed.

I have grown quite fond of using TYE as my daily driver, and going forward I am excited for other OAM related projects when TYE does eventually run its path. I do rely on TYE to do some of the heavy lifting of working with DAPR and until there is a replacement OAM project I cannot afford to switch to anything else.

However, it concerns me that the project team has not really pushed any code since August 2021. I know there have been the odd few updates since then, but not enough to really create a release, and what seems to be nothing of consequence. I also do not see the project team interacting with the issues board at all either.

Can anyone provide some insight into the future of this project? Should I be looking for alternatives? What are the alternatives?

**Comment by fntawiniga** [comment]
I have the same question but it seems the product is being worked on somewhere else. Please see version 0.11.0-* mentioned here #1265

**Comment by stephanjohnson** [comment]
So I add this issue, and all of a sudden there are a lot of new commits :)

> Please see version 0.11.0-* mentioned here #1265

I had a look at this version, but it has some problems with DAPR integrations, so I had to reset back to 0.10.

I'm closing this issue because it seems that I jumped the gun a little bit.
