### ISSUE TITLE
Cannot generate a docker image for 'backend' because docker is not running in azure pipeline

### ISSUE THREAD

**Issue by JhansiSai** [dotnet/tye#1306]
I have installed the docker by using the following command.
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

I am using "tye deploy" for deploying into the kubernetes through azure pipeline.

This is the yaml file for running the pipeline.

trigger:
- master

pool: 'default'

variables:
  solution: '**/*.sln'
  buildPlatform: ''
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'
      
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    version: "3.1.416"

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: CmdLine@2
  displayName: installing tye
  inputs:
    targetType: "inline"
    script: |
      dotnet tool install -g Microsoft.Tye --version "0.4.0-alpha.20371.1"

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: CmdLine@2
  displayName: 'set AKS context'
  inputs:
    script: |
      az acr login myContainerregistry
      az aks get-credentials

- task: CmdLine@2
  displayName: 'deploy'
  inputs:
    script: |
      docker version
      docker ps
      kubectl cluster-info
      kubectl get pods
      kubectl apply -f manifest.yaml
      tye deploy -v Debug

Here the error I am facing-
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by philliphoff** [comment]
@JhansiSai I'd suggest that this is unlikely a Tye issue, and more of an issue with creating a CI environment with a functioning Docker installation, and also note that Tye was (and is) not intended to be used for deployments of applications to a production environment.  That is to say, your mileage may vary.

All that said, I notice that the Docker version installed is rather old; I don't see what base environment is being used for this pipeline, but it may be that the two are no longer compatible.  Relatedly, the version of Tye being installed is also fairly old; we've just released 0.11.0.  Have you tried updating to later versions?  Other than that, I can only suggest looking through the pipeline logs to see if they might show issues during Docker installation that may be preventing it from starting.

**Comment by JhansiSai** [comment]
I have updated everything .net version(6.0) and Tye version(0.11.0).

These are the logs for the Docker installation.

Found tool in cache: docker-stable 17.9.0-ce x64
Prepending PATH environment variable with directory: C:\agent\_work\_tool\docker-stable\17.9.0-ce\x64
Verifying docker installation...
C:\agent\_work\_tool\docker-stable\17.9.0-ce\x64\docker.exe --version
Docker version 17.09.0-ce, build afdb6d4
Finishing: DockerInstaller

these are the logs for tye deploy-

Loading Application Details...
Verifying kubectl installation...
Verifying kubectl connection to cluster...
Processing Service 'backend'...
    Applying container defaults...
    Compiling Services...
    Publishing Project...
    Building Docker Image...
            time="2022-02-17T17:13:24+05:30" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: open //./pipe/docker_engine: The system cannot find the file specified." 
            context canceled
Drats! 'deploy' failed:
	'docker build' failed.
##[error]Script failed with exit code: 1
C:\WINDOWS\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
Finishing: AzureCLI

**Comment by philliphoff** [comment]
@JhansiSai I don't believe this to be an issue with Tye itself; Tye uses the `docker` CLI to manage images and containers, and the error shown is from the `docker` CLI, where it cannot connect to its Docker daemon, as it's likely not running.  That would point to an issue installing and starting the Docker daemon.  I also see that a very old version of Docker is being installed (17.9.0); I'd suggest moving to a more recent version and seeing if you have better luck.

**Comment by JhansiSai** [comment]
@philliphoff Actually I am using the self agent. This is the reason for getting that error. 
Thank You for your comments.
