### ISSUE TITLE
Origin of the name `Tye`

### ISSUE THREAD

**Issue by sethwenzel** [dotnet/tye#1330]
Hey Tye team!  This project is making our Dapr development very quick and easy locally, keep up the excellent work!

I was wondering what the name means.  Any insight into the word `Tye`?  Is this an acronym?  Does it mean something?

**Comment by PeterKnealeBizCover** [comment]
I think something more google-able would help, google keeps thinking i've mis-typed 'the'

**Comment by yilativ** [comment]
I'm offering my input to this question, but I thought it was related to the word `tie` so to tie/tye everything together.

**Comment by yilativ** [comment]
Nice! I wasn't too far off from thinking of `tie` 

> Etymology 1
A variant of [tie](https://en.wiktionary.org/wiki/tie#English).

Thanks for the response!
