### ISSUE TITLE
[Question] Trace/Debug events missing from Seq when using Seq extension

### ISSUE THREAD

**Issue by MiloszKrajewski** [dotnet/tye#1349]
For local environment / debugging I prefer to have Debug events to be logged.
Unfortunately, I was unable to configure service (I assume problem lies it is on a sending side) to send `Debug` events.

I tried:

```csharp
builder.Logging.SetMinimumLevel(LogLevel.Debug);
```

and:

```csharp
builder.Logging.AddFilter(level => true);
```

with no success.

`tye.yaml' is:

```
extensions:
  - name: seq
    logPath: "./.volumes/seq"
```

Is there a way to fix it, am I doing something wrong?

I understand, that I can host `Seq` as a container (not extension) and configure `Serilog.Sink.Seq` but I maybe there is something simpler / quicker I just missed.

**Comment by Phiph** [comment]
When I've used the Seq extension I get mixed results depending on the service type (Container, function or project)

I've always opted to use a Sink for serilog just to be sure, and switch out my sinks for my target environment!

I hope this helps.

**Comment by Phiph** [comment]
When I've used the Seq extension I get mixed results depending on the service type (Container, function or project)

I've always opted to use a Sink for serilog just to be sure, and switch out my sinks for my target environment!

I hope this helps.

**Comment by MiloszKrajewski** [comment]
That's what I did in then end. I mean just configured Seq as container and added Seq sink manually.
Thanks.
