### ISSUE TITLE
Support multiple applications sharing the same port

### ISSUE THREAD

**Issue by flcdrg** [dotnet/tye#138]
I have a ASP.NET Core application that currently runs as a self-hosted Windows Service or console app (using TopShelf, but not sure that's significant)

We need to run multiple instances of this app with different configurations. Instead of binding each instance to a unique port, it would be nicer to just have one consistent port and differentiate each instance off of the URL. eg.

* http://localhost:8080/AppA => c:\bin1\app.exe, 
* http://localhost:8080/AppB => c:\bin2\app.exe
* http://localhost:8080/AppC => c:\bin3\app.exe

or maybe:

* http://localhost:8080/App/A
* http://localhost:8080/App/B
* http://localhost:8080/App/C

I'm currently evaluating using ngnix to do this, but if Tye could do it simply, that would be very useful.

**Comment by flcdrg** [comment]
Possibly similar to the point raised in #137

**Comment by jkotalik** [comment]
I see the value. I think adding a section to the bindings here would probably be the right direction: https://github.com/dotnet/tye/blob/master/docs/schema.md#binding-properties for a path. 

For `tye run`, we already handle scenarios with proxying to multiple replicas today. I can see this also supporting multiple paths as well.

For `tye deploy`, I'd imagine this would be handled by whatever ingress is being used in kubernetes. This may be something we need to bootstrap though, as we don't do that today.

I think service discovery is an interesting problem as well. If someone wants to get the url of another service, they now need to account for the path to the application as well.

**Comment by flcdrg** [comment]
At the moment we're not running this in Kubernetes, so `tye run` is what I've been looking at so far.

Not sure how that would translate to running as a Windows Service or similar though - maybe that's a separate issue

**Comment by davidfowl** [comment]
@jkotalik This is more like adding support for ingress and being able to map different paths (or host names) to different services.

> Not sure how that would translate to running as a Windows Service or similar though - maybe that's a separate issue

Yes, please file that issue.

**Comment by davidfowl** [comment]
I thought about this a bit more and made this sample something you can use today:

https://github.com/dotnet/tye/pull/171

The most important pieces are here:

https://github.com/dotnet/tye/tree/316aacc01c901a1cb2824b116e6034ff05571189/samples/apps-with-ingress

This uses an nginx container as the proxy and routes traffic to each ASP.NET Core application. More on running ASP.NET Core behind nginx [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1).

I'm currently looking at what it would look like to turn ingress into a first class service type to remove some of this boilerplate.

**Comment by davidfowl** [comment]
Changes here https://github.com/dotnet/tye/pull/172. This adds support as a first class feature.

**Comment by davidfowl** [comment]
This is done
