### ISSUE TITLE
Resource consumption in tye dashboard

### ISSUE THREAD

**Issue by nebula2** [dotnet/tye#1432]
I think it would be a cool feature to see the resource consumption. 

Something like the output of `docker stats` would be more than enough.

I develop a system which needs to run on a bunch of low cost machines (1$-2$ VPS and a bunch of Pi's in k3s clusters) - therefore it is of importance that I monitor that.

**Comment by davidfowl** [comment]
Are you using tye in production or development?

**Comment by nebula2** [comment]
> Are you using tye in production or development?

development

**Comment by davidfowl** [comment]
Use the metrics that the currently shows?
