### ISSUE TITLE
[question] - tye.yaml encryption

### ISSUE THREAD

**Issue by rmszc81** [dotnet/tye#1435]
Hello everyone,
is there any way to encrypt the **tye.yaml** file to prevent someone with physical access to the file from reading it?

The reason is simple: as we use Tye to deploy on the physical equipment of some customers, we would like to have a mechanism to encrypt the contents of the file to prevent these same customers from having access to usernames and passwords of databases and/or other services that are part of of the ecosystem of our applications.

Thank you very much ^^.

**Comment by rmszc81** [comment]
3 months and not a single answer. Is this project dead?

**Comment by davidfowl** [comment]
Seems to overlap with the secrets idea: https://github.com/dotnet/tye/issues/30

**Comment by rmszc81** [comment]
> Seems to overlap with the secrets idea: https://github.com/dotnet/tye/issues/30

Yes, I'll close the ticket now, thanks.
