### ISSUE TITLE
[question] - how to specify a specific container (distro) in tye.yaml file

### ISSUE THREAD

**Issue by rmszc81** [dotnet/tye#1436]
Hello everyone,

one of the needs we have in our project is to use some containers with a specific distro (alpine, for example).

When we use asp.net core and .net containers, the containers used by tye are the default ones (debian).

is there any way to use some other distro? alpine linux, ubunty jammy linux, etc.?

Thank you very much!

**Comment by rmszc81** [comment]
3 months already and not even a single answer. I guess this project is dead...?

**Comment by Mrxx99** [comment]
See #1459

**Comment by rmszc81** [comment]
Thanks, I'll close this ticket.
