### ISSUE TITLE
Run service local or to external kubernetes service

### ISSUE THREAD

**Issue by allensiho** [dotnet/tye#1451]
Hi,

What is the best way to run a project locally in tye but also have the option to point to a deployed version of it on a kubernetes cluster?

I bleieve tye has an external service option?

**Comment by davidfowl** [comment]
What do you mean have the option to point to a deployed version? What are you trying to accomplish?

**Comment by allensiho** [comment]
Thanks,

I want to run the dot net project locally in tye.

Or ignore it and used another version that has been deployed to a k8s cluster

**Comment by allensiho** [comment]
So when I run tye i can optionally test some services to be local or run again and test a deployed version of it on the cluster whilst other projects that are local can interact with it.

Simple but Im just having priblems explaining it

**Comment by davidfowl** [comment]
Tye doesn't orchestrate anything running in kubernetes, it launches processes or containers locally and injects the right environment so you can discover other services. You can define a service that is a proxy to an external service so the right configuration is injected into the application that lets you do poor mans service discovery without changing the application (only the configuration changes).

**Comment by allensiho** [comment]
Ok thanks, so I need to create a new project that can proxy the requests externally?

Will YARP work?
Just learning these things.
Thanks

**Comment by davidfowl** [comment]
@allensiho Sure
