### ISSUE TITLE
Support for Dockerfile

### ISSUE THREAD

**Issue by adiazcan** [dotnet/tye#146]
### What should we add or change to make your life better?
Thinking on our projects, my team develop backend using dotnet core and the frontend using reactjs. 

If it possible to add a Dockerfile like we can add a dockerimage? 

In this case, Tye could build the Dockerfile, generate an appropiate dockerimage and run the image

### Why is this important to you?
With this option, we can use Tye for any type of projects that has a Dockerfile

**Comment by rynowak** [comment]
Thanks for the this feedback. I think we can already do this for a .NET project - if there's a dockerfile in the project directory we will use this rather than generating one. This doesn't really do everything that you're asking for though.

**Comment by rynowak** [comment]
Here's something I can imagine us doing. Supporting configuring services that build docker images and push, but aren't .NET based.

Currently we have some special behaviors for .NET projects:

- We build and run them
- We generate env-vars for service discovery in a format that .NET `Microsoft.Extensions.Configuration` understands
- We use ASP.NET Core's configuration setting to set listening URLs
- We put secrets on disk in k8s that match .NET's configuration format

Micronetes has a (currently undocumented) other schema for service-discovery + secrets that it can use when the service isn't a .NET project. We'd need to provide configuration support for describing how to build an image, as well plumb the service discovery stuff through all of these layers. We also need a non-ASP.NET Core centric way of telling an app about the listening port/address.

**Comment by adiazcan** [comment]
Ok, I know the limitations from the service discovery perspective. 

I don't know if it's possible or if an out of scope request for this project but why not get the service information from Dockerfile? Having service information on Dockerfile could be a requirement for non-dotnet projects.

**Comment by davidfowl** [comment]
> We build and run them

We only support .NET projects but you can launch an executable or run a docker image. Building a docker file seems logical as well.

> We generate env-vars for service discovery in a format that .NET Microsoft.Extensions.Configuration understands

We generate both a format that .NET expects and another format:

```
{SERVICENAME}_SERVICE_HOST - Host name of the service
{SERVICENAME}_SERVICE_PORT - Port of the service
{SERVICENAME}_SERVICE_PROTOCOL - Protocol of the service
```

> We use ASP.NET Core's configuration setting to set listening URLs

This [PR](https://github.com/dotnet/tye/pull/165/files) tries to improve the situation by providing port information via the PORT env variable.

This would be the same for deployment.

> We put secrets on disk in k8s that match .NET's configuration format

Right, we could also write another file format (or have a library that gets used by other platforms).

Here's an example I'm playing with:

```yaml
services:
- name: frontend
  executable: node
  args: frontend\app.js
  bindings:
    - autoAssignPort: true
- name: backend
  executable: go
  args: run backend\main.go
  bindings:
    - autoAssignPort: true
```

**Comment by jkotalik** [comment]
Keeping open as we only have support for tye run at the moment.
