### ISSUE TITLE
Dapr and Tye's Future Roadmap

### ISSUE THREAD

**Issue by leandromonaco** [dotnet/tye#1548]
In the latest Dapr's release notes I noticed that there is a new feature called "Multi-App Run", which seems to be pretty similar to the way Tye is configured to run multiple apps for local development.

Is Tye going to be merged with DAPR at some point or they will follow different paths?

https://blog.dapr.io/posts/2023/02/16/dapr-v1.10-is-now-available/

**Comment by karolz-ms** [comment]
Thanks for asking. We have no plans to merge DAPR CLI with Tye. 

More generally, as David mentioned [in this comment](https://github.com/dotnet/tye/issues/1459#issuecomment-1269276538), we (Microsoft) are very much interested in development tools for multi-service apps, but not working on Tye specifically, as of now.

**Comment by digitaldias** [comment]
Tye + Dapr = <3

But, it needs the ability to pause individually running projects to support the use of Dapr pubSub better. 
When I am developing my Dapr-based microservices solution, the need often arises to quickly debug one o the services. I can do this today by attaching my debugger to the Dapr instance, but it'd be even better if I could pause that running microservice in the Tye dashboard and then F5 my way through using VS.  A man can dream :)
