### ISSUE TITLE
Project was not running due to misdetection in ProcessRunner GetExePath - empty netcoreapp folders

### ISSUE THREAD

**Issue by btastic** [dotnet/tye#157]
### Describe the bug
I followed the tutorial and added several projects to my solution. All services were picked up correctly, started and showing up in the dashboard. One project seemed to run into an error though. 

![image](https://user-images.githubusercontent.com/6894999/77169077-317d2300-6ab9-11ea-994e-9b93a4773ab1.png)

The logging of the service in question looked like this:

`[<redacted>_cd5160ac-a]:dotnet "C:\Users\bkons\source\repos\<redacted>\<redacted>\bin\Debug\netcoreapp2.2\<redacted>.dll"`

The folder it is trying to run from has no files inside of it, which will lead to a failing dotnet command.

I had a look at the source and saw that you only take the first netcoreapp folder you can find, and assume that this is ok, but for one project it was not.

I have a working fix which involves iterating over all tmfs. Tests are still working and the service is running afterwards. I don't know whether this solution is good, but I would like to contribute.

Feel free to have a look at it
https://github.com/btastic/tye/commit/0b1d86146f39b31c93d4b8dcab3dedcaacffe481

### To Reproduce
Create an empty netcoreapp2.1 and netcoreapp2.2 folder in bin\debug and a valid netcoreapp3.1 or netcoreapp3.0 folder in bin\debug. The current code will take the first tfms regardless of a valid / found executable and return it.

### Further technical details
tye version from master at commit 8b81b3d4
platform is windows 10

**Comment by davidfowl** [comment]
That's a fine solution until we have msbuild more deeply integrated into run scenarios.

**Comment by davidfowl** [comment]
This is fixed with https://github.com/dotnet/tye/pull/188
