### ISSUE TITLE
Add service resiliency feature in generated dotnet services

### ISSUE THREAD

**Issue by amalkurup89** [dotnet/tye#166]
### What should we add or change to make your life better?

Add service resiliency similar to service discovery in the generated microservices

**Comment by rynowak** [comment]
Can you be more specific? Do you have any examples of thing syou want?

**Comment by amalkurup89** [comment]
Like an integration with framework like Polly and specify some standardized resilience policies in the generated microservices

https://github.com/App-vNext/Polly/blob/master/README.md

**Comment by davidfowl** [comment]
Are you saying there should be an SDK you can use that would use Polly under the covers or something else? Today there’s no library for tye, and the logic that needs to use retries can use Polly or anything else (like a service mesh) to add resiliency

**Comment by rynowak** [comment]
We already have integration with HttpClient and Polly - through HttpClient factory. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#use-polly-based-handlers

Right now tye provides an easier way to figure out what URLs you're trying to talk to and it should compose really well with client factory. So I'm not sure what else we'd add to make this better.

**Comment by rynowak** [comment]
We have no plans to do this right now as part of Tye. It would be difficult for us to generate code or magically light up a feature like this inside your applications. The libraries you need already exist external to Tye :+1:
