### ISSUE TITLE
We can't rely on host.docker.internal

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#176]
### Describe the bug
The hostname `host.docker.internal` is provided via tye service discovery to applications when doing a tye run, so they can communicate with the *load balancer* rather than a specific replica of another service.

The problem is that the port/url in question is running inside the host, not inside the container. The hostname `host.docker.internal` is part of docker for windows/mac and is not there on linux.

See: https://github.com/docker/cli/issues/2290

### To Reproduce

Run the `FrontendBackendRunTestWithDocker` - it's skipped on linux.

### Options

Some options to fix this. It's possible to get the IP of the host machine and pass it in to docker using `--add-host`. I've tried a few flavours of this, but It's getting late, and I desparately want to get the other 10 tests passing and checked in.

**Comment by christian-be** [comment]
Somehow I am hitting this issue again. All my containers are linux, but when I inspect the environment variables inside the containers, service uri's all have this format: _http://host.docker.internal:{port}/_ The bindings shown on the dashboard on the other hand show _http://localhost:{port}_

I'm running the projects via _tye run --container_. Would appreciate, if anyone could try to reproduce.

"Platform": "linux", mcr.microsoft.com/dotnet/core/runtime:3.1
Tye version: 0.4.0-alpha.20371.1+d7623120d66b85bfeda8ab69eb5ff792df6b7243
