### ISSUE TITLE
Detect whether we are running in tye

### ISSUE THREAD

**Issue by btastic** [dotnet/tye#177]
### What should we add or change to make your life better?
Make it possible to detect whether we are running in a tye environment.

### Why is this important to you?
In the sample code it suggests that I should grab the Url from the by tye declared environment variables for each service. That is great. But sometimes I want to deploy a debug configuration with my appsettings.json / appsettings.Development.json file and keep it that way. A way that I could think of is just declaring an environment variable called "TYE_ENABLED" or "TYE_ACTIVE" or just "TYE"? Something I can check within my application and decide whether to override the appsettings.json or keep it that way. Just using #if DEBUG would not suffice in all cases.

Or maybe there is already a way to detect this?

**Comment by davidfowl** [comment]
Why would you add that complexity to your application?

**Comment by btastic** [comment]
Well I was thinking about it in the same context of the other issue (#178) which is to have an easier way for me to determine my backend services. What would you suggest? Maybe I am overthinking this

**Comment by btastic** [comment]
With the other solution using a .yml file it seems I can work around this one. Thanks!
