### ISSUE TITLE
Use hosting port from launchsettings.json if not in use

### ISSUE THREAD

**Issue by btastic** [dotnet/tye#178]
### What should we add or change to make your life better?
Take the hosting ports from launchsettings.json if they are not in use. Otherwise generate a new hosting port.

Edit: just tried it, it does not seem to be very easy due to the nature of the generation of services. The services are not running yet, yielding a false when checking whether a port is in usage during launchSettings.json population..

### Why is this important to you?
I saw in the code that you actively decided to not use the ports from the launchsettings.json due to default settings. However, we have modified those to make the projects run locally. Our current dev setup looks like this: 4-5 Visual Studio instances, running each microservice and 1 Angular instance running the frontend.

Each visual studio instance of a .net core API project has its defined port values. Something like 5001, 6001, 7001, 8001 and so on. We'd love to use that with tye aswell.

Anyways, with how it is right now I always have to change the url within our angular frontend whenever I have to restart tye. This idea is not something essential, but would help a lot.

**Comment by davidfowl** [comment]
Not ideal but you can also specify the ports in tye.yaml

**Comment by btastic** [comment]
Oh, I didn't know about that. Will switch to that

**Comment by davidfowl** [comment]
Yep look at then example here https://github.com/dotnet/tye/blob/master/samples/multi-project/tye.yaml

**Comment by jkotalik** [comment]
Specifying ports in tye.yaml is probably the best course of action from porting from launchsettings.json.

One thought is to populate the tye.yaml file with the ports in the launchsettings.json when running `tye init`, however this runs into many issues:

- Again conflicts by default with two new projects
- It would clutter the tye.yaml file with a bunch of ports

Maybe we add a command to `tye init` which ports from launchsettings?

**Comment by davidfowl** [comment]
Closing this, with my latest change, we'll never use launchSettings ports. The ports of either specified or randomly assigned for http and https (if you have an ASP.NET Core project).
