### ISSUE TITLE
Meta: Provide a mechanism to receive periodic updates about tye

### ISSUE THREAD

**Issue by mcgwiz** [dotnet/tye#187]
### What should we add or change to make your life better?

Provide a link to an official announcements mechanism in README. Could just be GitHub Releases or a pinned Issue, either of which support subscriptions/notifications.

### Why is this important to you?

I want to stay current with the latest developments without having to actively pore through the repo every so often.

**Comment by rynowak** [comment]
> ### What should we add or change to make your life better?
> 
> Provide a link to an official announcements mechanism in README. Could just be GitHub Releases or a pinned Issue, either of which support subscriptions/notifications.
> ### Why is this important to you?
> 
> I want to stay current with the latest developments without having to actively pore through the repo every so often.

Awesome, this is great feedback. I'll discuss with the team and see what we want to do.

Our friends over at dotnet/efcore do the pinned issue: https://github.com/dotnet/efcore/issues/19549

We'll probably be doing a formal release every 4 weeks with:

- Release notes
- Blog post
- More demos and docs
- Some degree of testing
- Packages on nuget.org 😆

**Comment by rynowak** [comment]
Done. We're copying what EF is doing. 🥂 @ajcvickers  🎉 

Find the pinned issue here: https://github.com/dotnet/tye/issues/251

I've also updated the root README to suggest subscribing to it. Thanks for the idea!

**Comment by ajcvickers** [comment]
@rynowak I typically leave the most current update without the `details` expansion. Then add that in once there is a newer update. This way the newest update is always the most visible.

**Comment by rynowak** [comment]
Good idea. Will fix.
