### ISSUE TITLE
DevOps Samples

### ISSUE THREAD

**Issue by spboyer** [dotnet/tye#196]
Need to add samples in the docs for 
* DevOps deployment pipeline
* Github Action

Showing how to setup a GitHub action and/or DevOps pipeline to use `tye deploy`

**Comment by rynowak** [comment]
Super yes!

**Comment by davidfowl** [comment]
@spboyer are you going to do this? 😄

**Comment by rynowak** [comment]
A pretty simple AZDO one: https://github.com/staff0rd/DigitalIcebreakers/blob/master/azure-pipelines.yml
