### ISSUE TITLE
`tye run` runs the incorrect build version.

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/tye#205]
### Description

I attempted to use `tye run` against an existing sample solution of mine which I recently upgraded to .NET 5 from 3.1. The solution contains a front end application (Razor Pages) which calls a backend API service, similar to the sample.

`tye run` attempts to run the incorrect version.

### To Reproduce
I updated the front end to use the service discovery configuration.

When I execute `tye run`, the API project starts successfully. The web front end fails repeatedly (see output below).

The build produces output in the bin\Debug\netcoreapp5.0

The run step, however, seems to pick up an older build from the bin\Debug\netcoreapp3.0 folder, which exists from historical builds.

`dotnet "E:\Projects\Pluralsight\Worker Services Course\Tye Playground\src\TennisBookings.Web\bin\Debug\netcoreapp3.0\TennisBookings.Web.dll"`

**Full Output**
```
dotnet build "E:\Projects\Pluralsight\Worker Services Course\Tye Playground\src\TennisBookings.Web\TennisBookings.Web.csproj" /nologo
Restore completed in 70.83 ms for E:\Projects\Pluralsight\Worker Services Course\Tye Playground\src\TennisBookings.Web\TennisBookings.Web.csproj.
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
TennisBookings.Web -> E:\Projects\Pluralsight\Worker Services Course\Tye Playground\src\TennisBookings.Web\bin\Debug\netcoreapp5.0\TennisBookings.Web.dll
TennisBookings.Web -> E:\Projects\Pluralsight\Worker Services Course\Tye Playground\src\TennisBookings.Web\bin\Debug\netcoreapp5.0\TennisBookings.Web.Views.dll
Build succeeded.
0 Warning(s)
0 Error(s)
Time Elapsed 00:00:01.55
[tennisbookings.web_3504bce3-8]:dotnet "E:\Projects\Pluralsight\Worker Services Course\Tye Playground\src\TennisBookings.Web\bin\Debug\netcoreapp3.0\TennisBookings.Web.dll"
[tennisbookings.web_3504bce3-8]: Could not execute because the specified command or file was not found.
[tennisbookings.web_3504bce3-8]: Possible reasons for this include:
[tennisbookings.web_3504bce3-8]: * You misspelled a built-in dotnet command.
[tennisbookings.web_3504bce3-8]: * You intended to execute a .NET Core program, but dotnet-E:\Projects\Pluralsight\Worker Services Course\Tye Playground\src\TennisBookings.Web\bin\Debug\netcoreapp3.0\TennisBookings.Web.dll does not exist.
[tennisbookings.web_3504bce3-8]: * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

### Workaround

If I manually delete all bin folders and run `tye run` it works as expected.

The API worked without this but did NOT contain a netcoreapp3.0 folder in bin\Debug. It does contain netcoreapp2.2 and netcoreapp3.1 which seem to be ignored.

### Further technical details

`tye --version` = 0.1.0-alpha.20168.8+f45b9444d4894009bde48e2a3411a52dd09497b1
- Platform = Windows

**Comment by davidfowl** [comment]
This is fixed in the latest builds https://github.com/dotnet/tye/issues/184. Not multi-target projects are not supported.

**Comment by rynowak** [comment]
Also if we want to, we could support multi-targeting by adding a property. It's the kind of thing we should make the user's problem instead of guessing.

**Comment by davidfowl** [comment]
> Also if we want to, we could support multi-targeting by adding a property. It's the kind of thing we should make the user's problem instead of guessing.

Right, there should be a  `--framework` switch as well as a `--configuration` switch for https://github.com/dotnet/tye/issues/90

**Comment by davidfowl** [comment]
Closing this as fixed. I'll open issues for the other features
