### ISSUE TITLE
WSL not working completely

### ISSUE THREAD

**Issue by spboyer** [dotnet/tye#215]
- Dashboard works properly
- Cannot reach **localhost** for any application

Logs for **front-end**

```
Time Elapsed 00:00:11.18
[frontend_2701f98d-6]:dotnet "/home/spboyer/play/tyeplay/frontend/bin/Debug/netcoreapp3.1/frontend.dll"
[frontend_2701f98d-6]: �[40m�[32minfo�[39m�[22m�[49m: Microsoft.Hosting.Lifetime[0]
[frontend_2701f98d-6]: Now listening on: https://localhost:37077
[frontend_2701f98d-6]: �[40m�[32minfo�[39m�[22m�[49m: Microsoft.Hosting.Lifetime[0]
[frontend_2701f98d-6]: Now listening on: http://localhost:44665
[frontend_2701f98d-6]: �[40m�[32minfo�[39m�[22m�[49m: Microsoft.Hosting.Lifetime[0]
[frontend_2701f98d-6]: Application started. Press Ctrl+C to shut down.
[frontend_2701f98d-6]: �[40m�[32minfo�[39m�[22m�[49m: Microsoft.Hosting.Lifetime[0]
[frontend_2701f98d-6]: Hosting environment: Development
[frontend_2701f98d-6]: �[40m�[32minfo�[39m�[22m�[49m: Microsoft.Hosting.Lifetime[0]
[frontend_2701f98d-6]: Content root path: /home/spboyer/play/tyeplay/frontend
```

### Further technical details

WSL2
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
Tye Version

`tye --version` `0.1.0-alpha.20168.8+f45b9444d4894009bde48e2a3411a52dd09497b1`

**Comment by jkotalik** [comment]
I'm not seeing the same behavior when running WSL2. Can you not access the application at all (via 127.0.0.1 either? It's odd to me that you can hit the dashboard but not the services.

**Comment by spboyer** [comment]
@jkotalik - no applications are avail via the browser or cmd line on the windows side.

* curl from WSL no issues. 
* Dashboard is good
* Tried with SSL from Windows - `curl: (60) SSL certificate problem: unable to get local issuer certificate`
* Windows no SSL - 'curl: (7) Failed to connect to localhost port 41513: Connection refused'

**Comment by spboyer** [comment]
WSL is working under http. HTTPS to be addressed under other issues.

**Comment by rynowak** [comment]
Awesome! Glad to find out it wasn't something mysterious.
