### ISSUE TITLE
Pull the docker image before running

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#222]
Today run implicitly pulls the image but the ux isn't great. See https://github.com/dotnet/tye/issues/200. Instead, we should pull the image explicitly before running.

**Comment by davidfowl** [comment]
I'm slightly worried about the performance impact of pulling everytime, maybe it's better to show the docker pull output directly in the console output  in tye.

**Comment by rynowak** [comment]
Another possible advantage would be it can mitigate failing/badly-written apps by forcing everything to wait. Like, if you want to call into rabbitmq, but it's taking 2 minutes to pull the image, that's not ideal.

**Comment by davidfowl** [comment]
That's true, but it would happen once. OK so maybe I'll add a phase that pulls all of the docker images before running either a process or docker container.
