### ISSUE TITLE
Support multi-repo projects

### ISSUE THREAD

**Issue by bravecobra** [dotnet/tye#224]
Tye currently works perfectly in a mono repo setup where `dotnet build` is enough to create your binaries. How would you run all your microservices with tye if they are maintained in a multiple repositories, each with their own build pipeline? Each repo would have solution file. Combining them into one seems error-prone.
Would you use a separate git repo with git submodules? What if you already have build pipelines defined to build one particular project?
If tye.yaml would allow to add a project location to be included outside the current tree, a build command with a context and a run command with context, that'd be nice. That would allow to include 
a project outside the current directory to be included in the setup. Deploying however would be more challenging.

Any other suggestions for multi repo microservices?

**Comment by davidfowl** [comment]
> If tye.yaml would allow to add a project location to be included outside the current tree, a build command with a context and a run command with context, that'd be nice. That would allow to include
a project outside the current directory to be included in the setup. Deploying however would be more challenging.

It does allow for that. I think you’d either move the tye.yaml outside of the repository and work that way or use another repository with sub modules if you wanted to check them in.

**Comment by bravecobra** [comment]
@davidfowl indeed, that would have been my first attempt to try out. 
Would #146 help when that other project is not a .net core project? Being able to rebuild those images upon run, just like docker-compose, would be a welcome addition. Or can we hook into/trigger the build pipeline of a non .net project?

**Comment by davidfowl** [comment]
> Would #146 help when that other project is not a .net core project? 

Yes it will help. Today you can run arbitrary executables but those aren'y deployable. Adding docker file support would let you build and run images for other platforms (similar to compose).

**Comment by rynowak** [comment]
Closing in favor of #239 which has more info. We're working on this 👍
