### ISSUE TITLE
Configuration input and model validation

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#232]
Today invalid configuration show awful hard to read de-serialization exceptions in the console. Once that succeeds, it's possible to have an invalid configuration model and we don't have much validation in place today (besides very basic required fields, like the name of services).

We need to do both input validation and model validation:
- **Input validation** - Making sure the configuration schema is correct (type checking).
- **Model validation** - Making sure the configuration is valid after it is correctly parsed.

**Input Validation**
- [x] - Improve the input validation we need to write custom de-serialization logic and give nice errors with the line number in the file etc.
- [x] - Replicas can't be negative

**Model Validation**
- [x] - https://github.com/dotnet/tye/issues/106 Tye should throw when multiple bindings are specified without names 
- [x] - All services should have a name (it's required)
- [x] - Ingress protocol should be http or https
- [x] - Ingress must point to a valid service
- [x] - Multiple bindings cannot have the same name
- [x] - Services cannot have the same name
- [x] - Services cannot be bound to the same port
- [x] - For services, image, project and executable are mutually exclusive

**Comment by davidfowl** [comment]
Did you implement all of the model validation rules?

**Comment by jkotalik** [comment]
Thx.

**Comment by rynowak** [comment]
bop it.
