### ISSUE TITLE
Docker Debian Based Images assumed with TFM Pattern

### ISSUE THREAD

**Issue by spboyer** [dotnet/tye#240]
https://github.com/dotnet/tye/blob/2a0ffaf88cc135a3fcdd41f7ae83eb3c1dd69af9/src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs#L88

his pattern would assume that all development, if using Linux containers, would be done on Debian based containers given the TFM base image is always such. How would we specify an alpine or other flavor? Should we consider looking leveraging [Container MS Build Properties](https://docs.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties?view=vs-2019) or expanding upon them?

i.e.

```xml
<PropertyGroup>
   <DockerbaseImage>{TFM}-alpine</DockerbaseImage>
</PropertyGroup>
```

**Comment by rynowak** [comment]
Triage: the container tools package requires a dockerfile, which we want to avoid in a lot of cases. It seems like a good idea that we're support some customization via MSBuild or another path that doesn't require a dockerfile 👍

**Comment by rynowak** [comment]
We're open to a PR for this - using the project file to feed the base image to the dockerfile generator for both run and deploy.

We're open to a pr that looks like:

```C#
<PropertyGroup>
   <ContainerBaseImage>...</ContainerBaseImage>
   <ContainerBaseTag>...</ContainerBaseTag>
</PropertyGroup>
```

`ContainerBaseImage` specifies the repository.

`ContainerBaseTag` specifies the tag.

Most users will want to end up changing `ContainerBaseTag` if they are using a supported .NET runtime image, the choice of OS is represented in our images by different tags.
