### ISSUE TITLE
tye run on specific service seem not working

### ISSUE THREAD

**Issue by thangchung** [dotnet/tye#246]
### Describe the bug
`tye run` on specific service name seems not working

### To Reproduce
I have tried to run the service with `tye` as following

```bash
$ tye run inventory-api
```

But it always notified `The file 'inventory-api' could not be found.`. I know that we can specify the path to .csproj, but I see the docs at https://github.com/dotnet/tye/blob/master/docs/frontend_backend_run.md can run the `frontend` as 

```bash
$ tye run frontend
```

My source code is at https://github.com/thangchung/practical-dapr/blob/feature/docker-stuffs/tye.yaml

### Further technical details

- Include the output of `tye --version`
0.1.0-alpha.20175.1+6d4910b1f54b7e98100c8e65857f2baeb578de1b

- The platform (Linux/macOS/Windows)
Windows 10

**Comment by thangchung** [comment]
Sorry, my bad. It should be `tye run src/Inventory/CoolStore.InventoryApi`.

But I have a question. Can we run the docker image from `tye run`?

**Comment by davidfowl** [comment]
> tye run on specific service name seems not working

This doesn't work today. You can `tye run` a specific project (as you have outlined) but that will essentially be a `dotnet run` on that project with a nice dashboard.

Why do you want to tye run a specific project?

> But I have a question. Can we run the docker image from tye run?

Depends on what you mean. You can `tye run --docker` and it will run your projects inside of a container but it won't build container images. `tye build` will build container images for your projects and store them in you local docker image repository.

**Comment by davidfowl** [comment]
@thangchung Some things that are interesting related to your project:
- We're adding dapr support https://github.com/dotnet/tye/pull/250
- You don't need docker compose (tye should be able to express both container and project dependencies)
- You don't need to specify ports, you can but they aren't necessary. Tye will inject environment variables into the process/container with the right host names and ports.

**Comment by thangchung** [comment]
Cool @davidfowl. I would like to see the whole picture of how tye and Dapr work together to simplify the microservice development.

**Comment by thangchung** [comment]
Hi @davidfowl,

How can I get the https/grpc port and protocol of gRPC service. 

I hosted it using `tye` as 

![image](https://user-images.githubusercontent.com/422341/77933941-99154880-72d9-11ea-8b58-319ce12caf73.png)

I want to get https://localhost:64572 for inventory-api. When I using 

```csharp
var host = _config["service:inventory-api:host"];
var port = _config["service:inventory-api:port"];
```

It hasn't gotten correctly (only get **localhost:64571**, the `http` part). But I want to get **localhost:64572**, the `https` part)

Currently, I get the `inventory-api` app as below

```csharp
var protocol = Environment.GetEnvironmentVariable("INVENTORY-API_HTTPS_SERVICE_PROTOCOL");
var port = Environment.GetEnvironmentVariable("INVENTORY-API_HTTPS_SERVICE_PORT");
var host = _config["service:inventory-api:host"];
var url = $"{protocol}://{host}:{port}";
```

![image](https://user-images.githubusercontent.com/422341/77934443-49834c80-72da-11ea-8cf7-f482d65756ab.png)

It worked, but I know it isn't the correct way to call to gRPC service. Could you tell me how can I get the host/port for the https scheme?

**Comment by rynowak** [comment]
Sorry, we lost track of this. Service discovery is documented here: https://github.com/dotnet/tye/blob/master/docs/reference/service_discovery.md#how-it-works-uris-in-development

This would use the config key `service:<service name>:https:port`

**Comment by thangchung** [comment]
Thank you. It worked correctly
