### ISSUE TITLE
Tye vs Azure Dev Space

### ISSUE THREAD

**Issue by Eneuman** [dotnet/tye#247]
Hi
I watched the Asp.net Standup show where Tye was presented. It looks interesting. How does Tye positioning itself compared to Azure Dev Spaces? They seem to try and solve the same thing.
Regard
Per

**Comment by rynowak** [comment]
Hi, Thanks for your question.

We're experimenting with lots of options and ideas to try and improve developer productivity. The remote development demo we showed is actually a collaboration with the dev spaces team. Part of this experiment would be see a remote development workflow could be integrated with a CLI like Tye.

In terms of positioning:

- Azure Dev Spaces is a product that you can use, with documentation and support. Tye is not 😆 - Azure Dev Spaces is a full-featured offering focused on doing development and testing with a k8s cluster. Tye is trying to solve a variety of productivity problems. We might decide that remote/attached development fits in to Tye, or it might never go further than the demo you saw.

I hope this clears things up.
