### ISSUE TITLE
run tye results to The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by tomasherceg** [dotnet/tye#248]
### Describe the bug

I have one repo with multiple .NET Core services that are using a shared class library project (via ProjectReference). 

When I use `run tye`, it tries to build all of them, some of the projects fail with the following exception:

```
The process cannot access the file 'D:\Work\OpenEvents\src\OpenEvents\OpenEvents.Model.Payments\bin\Debug\netstandard2.0\OpenEvents.Model.Payments.deps.json' because it is being used by another process.
```

It happens pretty randomly. 

It never happens with `--no-build` flag.

I assume that the issue is caused by the fact that all projects are built independently and the builds run in parallel, so when they try to write the DLL of the shared project (which all of them need to build), some of them just fail. I haven't found an option to build them all together using the SLN file.

### Further technical details

- Include the output of `tye --version`: **0.1.0-alpha.20175.1+6d4910b1f54b7e98100c8e65857f2baeb578de1b**
- If possible rerun the command with `-v debug` and include the output: **not helpful, I am getting The file '-v' could not be found.
Unrecognized command or argument 'debug'**
- The platform (Linux/macOS/Windows): **Windows**

**Comment by davidfowl** [comment]
Yea... This is because we do build multiple projects in parallel without looking at the build graph. We may need to remove the parallelism for now.

**Comment by tomasherceg** [comment]
I think that most users will have one `.sln` file. What about an option in `tye.yml` to build the entire solution instead of individual projects?
