### ISSUE TITLE
Pass additional arguments to docker run

### ISSUE THREAD

**Issue by tomasherceg** [dotnet/tye#249]
### What should we add or change to make your life better?

I tried to add Mongo DB as a Docker container, but I couldn't mount the volume correctly on Windows using `tye.yml`. 

The problem is a combination of the following things:
* Mongo doesn't work with volumes mapped to Windows filesystem (`-v c:/something:/data/db`). It needs the named volume (which is mapped to a filesystem in the host VM) - I need to run `docker volume create --name=mongodata` (I can do it manually, it's a one-time operation), and then `docker run ... -v mongodata:/data/db`.
* When I use `mongodata` as `source` in `tye.yml`, it thinks that it's a relative path and make a full path for it - so `c:/something/mongodata` is passed)
* I haven't found a way how to pass additional arguments to `docker run` using `tye.yml` or how to work with named volumes

### Why is this important to you?

I can work-around this by running the container on my own, but I think that Mongo is quite a popular database so more people can run into this issue, and I also think that `tye.yml` could offer more flexibility because many containers need some special configuration.

Anyway, GREAT JOB! I love Tye so far. ❤

**Comment by rynowak** [comment]
Thanks! Recategorizing this as a bug since something doesn't work.

**Comment by davidfowl** [comment]
> When I use mongodata as source in tye.yml, it thinks that it's a relative path and make a full path for it - so c:/something/mongodata is passed)

I think this might be the think to fix here. We can support a -name on volumes instead of source.

> I haven't found a way how to pass additional arguments to docker run using tye.yml or how to work with named volumes

This is also something we should support.

**Comment by davidfowl** [comment]
The PR for named volumes is up

**Comment by davidfowl** [comment]
I've fixed the named volumes, support, will leave this open for docker run command support. I'm a bit hesitant to give that amount of power for now.

**Comment by tomasherceg** [comment]
@davidfowl Wow, that was quick! The named volume support is great - this should help everyone who is using Mongo. I agree that giving the option to specify any docker run args can be dangerous.

**Comment by rynowak** [comment]
Closing this because we don't plan to directly support configuring the args of `docker run` right now. If you have something you need, please ask, we'd love to talk to you.
