### ISSUE TITLE
How to set ASPNETCORE_ENVIRONMENT?

### ISSUE THREAD

**Issue by thoemmi** [dotnet/tye#258]
For project-type services the environment variable `DOTNET_ENVIRONMENT` is set to `Development`:

https://github.com/dotnet/tye/blob/fca277c102121da1a50e9cc918e2aa81e0a63d5e/src/Microsoft.Tye.Hosting/ProcessRunner.cs#L127-L131

However, `ASPNETCORE_ENVIRONMENT` is not set. Is this a shortcoming, or do I have to specify it in my _tye.yaml_ explicitely?

**Comment by davidfowl** [comment]
We need to set both, this is a bug. This works on both ASP.NET Core and Worker apps in 3.1 but ASP.NET Core < 3.1 this doesn't work. We'll fix this by setting both things.

**Comment by davidfowl** [comment]
As a workaround, you can set it in `tye.yaml`.

**Comment by thoemmi** [comment]
> As a workaround, you can set it in tye.yaml.

That's what I've done 😉
