### ISSUE TITLE
Network configuration for Docker services and usage of existing networks

### ISSUE THREAD

**Issue by alexfdezsauco** [dotnet/tye#282]
### What should we add or change to make your life better?

For a reason I just created a docker container and a network that its life-cycle is not controlled by Tye.  For instance I have a postgres container that live forever on my development computer with a lot of databases.

But at some point I want to integrate a Tye hosted solution to an existing network. For instance, the solution includes a keycloak but I want to use an existing database that is actually in the postgres container not hosted by Tye.  

keycloak and postgres are a good scenario because,  at least on docker for windows, both containers have to use the same network.  So, I created a network outside Tye and I want launch a container with Tye that reference such network.

### Why is this important to you?

Because my development machine could be a mess and I want to maximize the options.

**Comment by davidfowl** [comment]
I'd prefer it if containers weren't individually configurable on a specific network but I'm find connecting all containers to an existing network that can be specified. Ideally tye wouldn't end up being just as noisy as docker-compose (that's actually the point) but letting you specify the network is a fine way to allow containers created by tye to integrate with another container network.

How does that sound?

**Comment by alexfdezsauco** [comment]
It sounds good.

**Comment by davidfowl** [comment]
Done!
