### ISSUE TITLE
Document how to keep the tool updated to latest released version

### ISSUE THREAD

**Issue by luisgizirian** [dotnet/tye#283]
### What should we add or change to make your life better?
Please document how to keep the dotnet global tool up-to-date with the latest version

I'm on 0.1.0-alpha.20175.1 (as the getting started doc specifies. I'm trying the DAPR recipe. Getting a "Property 'extensions' not found" message. Then, assuming i'm on an older release.

The only way (to my knowledge) to find out the current release was to run `dotnet tool update -g Microsoft.Tye --add-source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json` . As no version is specified, got this 

```
error NU1103: Unable to find a stable package microsoft.tye with version 
error NU1103:   - Found 62 version(s) in dotnet-core [ Nearest version: 0.1.0-alpha.20181.1 ]
error NU1103:   - Found 0 version(s) in /usr/share/dotnet/sdk/NuGetFallbackFolder
error NU1103:   - Found 0 version(s) in nuget
error NU1103:   - Found 0 version(s) in bedrockframework
error NU1103:   - Found 0 version(s) in featherhttp
Tool 'microsoft.tye' failed to update due to the following:
The tool package could not be restored.
Tool 'microsoft.tye' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```
**So, that's how I know the latest (nearest, in the second row) version. Is there a handier way to do it?**

### Why is this important to you?
For quick catch up.

**Comment by rynowak** [comment]
You can do this like the following:

```C#
dotnet tool update -g Microsoft.Tye --version "0.1.0-*" --add-source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
```

For some reason, you need to manually specify `--version "0.1.0-*"` to allow the use of a prerelease version. I need the quotes as well on ZSH - YMMV.

I'll update the docs to include this info.

**Comment by luisgizirian** [comment]
Sorry @rynowak . I've rushed into closing the issue. Should've waited for action confirmation on your end? Please close it when you consider.

**Comment by rynowak** [comment]
I'm ready to close it. Please let us know if you need anything else 😁
