### ISSUE TITLE
How to change redis port?

### ISSUE THREAD

**Issue by codeConcussion** [dotnet/tye#291]
I'm not sure if this is a bug or not, but I would like to be able to change the redis port from the default - 6379 to 6380.

I've tried changing the binding. That generates the docker argument `-p 6380:6380` which is incorrect. I want it to be  `-p 6380:6379`.

I've tried passing that as an argument, `args: "-p 6380:6379"`, but that looks like it's passing it to redis rather than to docker.

I've tried modifying a bunch of environment variables that I found from the command line when it starts the container - `ASPNETCORE_URLS, PORT, SERVICE__REDIS__PORT, REDIS_SERVICE_PORT`. I don't see that those changes do anything.

Any ideas? I'd like to do the same with RabbitMq and Seq if I can get this figured out.

**Comment by codeConcussion** [comment]
Of course after I post an issue I find a workaround. Using `args: "redis-server --port 6380"` along with the standard port binding seems to work. Is this the recommended way of handling this?

I also still need a way to get RabbitMq and Seq working on non-default ports.

**Comment by davidfowl** [comment]
```yaml
services:
 - name: redis
   image: redis
   bindings:
    - port: 6380
      containerPort: 6379
```
