### ISSUE TITLE
Print output for msbuild pre-amble

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#295]
### What should we add or change to make your life better?
We need to print out the something while we're building the tye.yaml model internally since it involves msbuild and could be slow. Today it looks as though the tool itself is just really slow to boot on commands.

### Why is this important to you?
It'll be a better user experience.

**Comment by rynowak** [comment]
We shouldn't print MSBuild's header because that will be one-per-project. We should just print a progress message like

```
Loading Application Details...
```

**Comment by davidfowl** [comment]
Yea the title is wrong but the issue text is correct
