### ISSUE TITLE
Internal builds failing to find Microsoft.Tye.Extensions.Configuration.pdb

### ISSUE THREAD

**Issue by jkotalik** [dotnet/tye#304]
Internal builds have been failing to find the `Microsoft.Tye.Extensions.Configuration.pdb` file in builds. This has failed the last 3 internal builds: https://dnceng.visualstudio.com/internal/_build/results?buildId=590188

**Comment by jkotalik** [comment]
Guess:

netstandard2.0, set symbol type to embedded.

**Comment by davidfowl** [comment]
Fixed now?

**Comment by rynowak** [comment]
Fixed.
