### ISSUE TITLE
Tye Breaking Changes

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#312]
# Summary

We'll use this issue to announce breaking changes we're making to Tye that will be impactful to users. The idea is similar https://github.com/dotnet/tye/issues/251 but instead of status and plans, we'll use this communicate about changes that are impactful and how to react to them.

Only team members can post on this issue, so it will be low traffic. Subscribe to notifications on this issue if you want to be notified when there's a new post 👍 

## About breaking changes

Keep in mind that Tye is an experimental project. We expect to make frequent changes and we expect those changes to be impactful.

If you want a more stable experience, use the builds on nuget.org (coming soon). We'll be pushing updates to nuget.org approximately once every 4 weeks. 

Using our CI builds is a great way to participate in development, but we don't promise that everything is fully-baked 100% of the time.

**Comment by rynowak** [comment]
## Significant updates to bindings env-vars and secrets

We're introducing a library (`Microsoft.Tye.Extensions.Configuration`) to make it straightforward to use Tye's service discovery features for all of the following cases:

- Getting the URI of another service
- Getting the connection string to a data source
- Working in development
- Using secrets in production

This should streamline many of the existing experience that used copy-pasted code, or often in our examples where they used slightly different versions of copy-pasted code 👿.

To get this all in-line we've done some design work around how these features can work best, which results in some breaking changes. I'll list them here and link to a longer doc I've added the describes how this works. If you stick to using our library you should be fine.

https://github.com/dotnet/tye/blob/3248ea9ec583c5ca8977c9ad9a661c18566c2f0d/docs/service_discovery.md

## Changes

We've replaced `connectionstring` as a key in env-var and configuration key names with `connectionstrings` (note the plural). Using `connectionstring` was incompatible with the existing `GetConnectionString` method from `M.E.Configuration`.

Bindings now *either* produce a protocol/host/port triple OR a connection string. For deployed applications we need to know if you expect a connection string or a URI, so we're making a switch to this. We want to try keeping URIs and connection strings separate and see if that's more simple to understand and use.

Connection strings now have templating features. Rather than building connection strings in your application, you can compose them in tye.yaml. Our tutorial now includes this for redis, as do most of our other samples.

**Comment by rynowak** [comment]
## Changes to feeds used by Tye and Microsoft.Tye.Extensions.Configuration

The feed that we publish packages to has changed. We now push to the `dotnet5` feed. Our getting started instructions for using CI builds will be updated accordingly.

If you have a nuget.config that you just to pull in the `dotnet-core` feed, this should updated to use `dotnet5`.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet5" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by jkotalik** [comment]
We will be addressing breaking changes in a different way going forward.
