### ISSUE TITLE
Add exponential backoff for process restarts in tye run

### ISSUE THREAD

**Issue by jkotalik** [dotnet/tye#325]
When a service is constant failing to start, it doesn't make a ton of sense to have the app constantly fail to start, spamming the logs without backoff.

**Comment by rynowak** [comment]
Yes please. or even just linear - some kind of backoff 👍

**Comment by davidfowl** [comment]
Today it waits 5 seconds before trying in the process runner. Docker uses restart policies

**Comment by rynowak** [comment]
We should see if docker has a feature for backoff. We'd prefer not to build a new feature for the docker part.

**Comment by jkotalik** [comment]
Will be fixed by https://github.com/dotnet/tye/pull/444
