### ISSUE TITLE
Improve logs for publish failing for tye deploy

### ISSUE THREAD

**Issue by jkotalik** [dotnet/tye#339]
Currently, if dotnet publish fails, the logs look like:
```
Processing Service 'vote'...
    Compiling Services...
    Publishing Project...
Drats! 'deploy' failed:
        'dotnet publish' failed.
```

This should output the reason why dotnet publish failed.

**Comment by rynowak** [comment]
yeah agreed. We currently capture all of this output, but don't y33t it out when the command fails. https://github.com/dotnet/tye/blob/master/src/Microsoft.Tye.Core/PublishProjectStep.cs#L39

We should audit all of the places where we shell out.

**Comment by rynowak** [comment]
We should look at all of the usage of `output.Capture` - they are all places where we could have a similar bug.

**Comment by jkotalik** [comment]
The bug here is that dotnet publish, when there is an exit code of 1, doesn't actually write to stderr. Therefore, there isn't anything captured or written.
