### ISSUE TITLE
Can't run Tye for a solution

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/tye#345]
Followed the steps in the [Front End / Back End tutorial](https://github.com/dotnet/tye/blob/master/docs/tutorials/hello-tye/00_run_locally.md) I've been able to successfully create two F# ASP .NET projects which Tye can launch individually. However, when I try to launch them both via a solution file, Tye says: `"Drats! 'run' fail: No services found in "microservice.sln"`.

```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26124.0
MinimumVisualStudioVersion = 15.0.26124.0
Project("{F2A71F9B-5D33-465A-A702-920D77279786}") = "frontend", "frontend\frontend.fsproj", "{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}"
EndProject
Project("{F2A71F9B-5D33-465A-A702-920D77279786}") = "backend", "backend\backend.fsproj", "{C2559B7D-07D4-4096-9929-1AFB9A324022}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Debug|x64 = Debug|x64
		Debug|x86 = Debug|x86
		Release|Any CPU = Release|Any CPU
		Release|x64 = Release|x64
		Release|x86 = Release|x86
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Debug|x64.ActiveCfg = Debug|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Debug|x64.Build.0 = Debug|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Debug|x86.ActiveCfg = Debug|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Debug|x86.Build.0 = Debug|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Release|Any CPU.Build.0 = Release|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Release|x64.ActiveCfg = Release|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Release|x64.Build.0 = Release|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Release|x86.ActiveCfg = Release|Any CPU
		{CB8B3182-36E7-49C0-A7DC-BB39542B15B7}.Release|x86.Build.0 = Release|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Debug|x64.ActiveCfg = Debug|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Debug|x64.Build.0 = Debug|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Debug|x86.ActiveCfg = Debug|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Debug|x86.Build.0 = Debug|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Release|Any CPU.Build.0 = Release|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Release|x64.ActiveCfg = Release|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Release|x64.Build.0 = Release|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Release|x86.ActiveCfg = Release|Any CPU
		{C2559B7D-07D4-4096-9929-1AFB9A324022}.Release|x86.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
```

Running from dotnet 3.1.2.

**Comment by davidfowl** [comment]
Do those projects have launchSettings.json under properties? Try running tye init on the solution as well, that will show if it can find anything

**Comment by isaacabraham** [comment]
OK, probably it's because I've created these projects as standalone console apps rather than as webapi etc. projects - I suspect I need the `launchSettings.json` and maybe change the SDK. Let me check!

**Comment by isaacabraham** [comment]
Yep, adding some launchsettings.json files fixed it. I had a (brief) look through the source but couldn't find the source of the issue - I was thinking that it somehow hadn't identified the projects in the solution.

Maybe consider making the launch settings file optional, or at least documenting / giving a more detailed error? I got confused because Tye works fine at the project level without the launch settings, but not at the solution level.

**Comment by jkotalik** [comment]
> I got confused because Tye works fine at the project level without the launch settings, but not at the solution level.

That's a good point that we aren't consistent there between running a single project versus running multiple projects. We should fix that.

In this release, we added a check to ensure tye will only launch projects that have a launchsettings.json in the project. This also applies to the tye.yaml generation from `tye init`. This is to prevent running projects that shouldn't be run, like test projects.

I think we should log each time we skip a project (or something to that effect).

**Comment by isaacabraham** [comment]
@jkotalik out of curiosity, is the launch settings file actually required or just used as a marker to include the project? If the latter - consider using another mechanism.

**Comment by jkotalik** [comment]
I believe it's only used as a marker. I agree, it isn't a great mechanism.

I'll file some follow up issues as this issue has been sidetracked.

**Comment by rynowak** [comment]
> If the latter - consider using another mechanism.

It's only a marker.

Do you have a suggestion? We're trying to narrow down the set of projects we have to load into MSBuild (~200ms each). We could use MSBuild to get the *real* answer about whether a project is executable, but it would add slowness.

**Comment by isaacabraham** [comment]
@rynowak put it this way - I had to ask on Twitter and spent around 15 minutes figuring it out. It's not needed to host an ASP .NET web app - I just usually start with a console exe, add the Saturn nuget package and off I go.

I would probably start by simply scanning all projects by default (and, yes, check if they are executables), but provide users with the ability to add either a whitelist or blacklist as needed. This would lower the barrier to entry and remove this entire issue.

Out of curiosity, why does it take 200ms+ to check if a project is an exe? Can you not just find all cs/fsproj files and check for the existence of the appropriate bit of text e.g. `<OutputType>Exe</OutputType>` or am I just being naiive here :-)

**Comment by davidfowl** [comment]
> or am I just being naiive here :-)

Yes 😄 . We use msbuild APIs instead of scanning XML files because the latter is fragile. That said, since we're already not using msbuild during init, it might be find to look at that property as well.

**Comment by rynowak** [comment]
> provide users with the ability to add either a whitelist or blacklist as needed. This would lower the barrier to entry and remove this entire issue.

Generating a `tye.yaml` using `tye init` and customizing it is this feature 😆 

We could improve the documentation here but that doesn't help if you don't know that you've got a problem. 

It looks like the console template does include `<OutputType>Exe</OutputType>`. It seems fine to use that a heuristic as well.

**Comment by isaacabraham** [comment]
@rynowak great - so just improving the documentation and secondly changing the default behaviour to be a little more "greedy" might be what you're looking for. And removing the dependency on the `launchsettings.json` at the same time!
