### ISSUE TITLE
Figure out how to inject configuration

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#35]
Currently you can interact with secret-based bindings via something like:

```csharp
                .ConfigureAppConfiguration(config =>
                {
                    if (Directory.Exists("/var/tye/bindings/"))
                    {
                        foreach (var directory in Directory.GetDirectories("/var/tye/bindings/"))
                        {
                            Console.WriteLine($"Adding config in '{directory}'.");
                            config.AddKeyPerFile(directory, optional: true);
                        }
                    }
                })
```

This is ugly boilerplate that we don't want to put in every project, and it requires an extra package reference (key per file).

Using configuration via files is valuable because:

- more securities
- values can be updated

**Comment by ChadJessup** [comment]
> Or a volume we inject with the binary.
> 
> ```
> /var/tye/framework/Microsoft.Configuration.Tye.dll 
> ```
> 
> ```
> DOTNET_STARTUP_HOOKS=/var/tye/framework/Microsoft.Configuration.Tye.dll
> ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.Configuration.Tye
> ```

This is more of a curiosity, as I didn't know about `DOTNET_STARTUP_HOOKS`, how can this injection be done safely in regards to malicious code being injected instead?

**Comment by davidfowl** [comment]
> This is more of a curiosity, as I didn't know about DOTNET_STARTUP_HOOKS, how can this injection be done safely in regards to malicious code being injected instead?

If somebody can inject environment variables into your process, you already have a security problem.

**Comment by ChadJessup** [comment]
True, and point taken, I was thinking more along the lines of hijacking a dll's name which is a lot easier (especially since these dependencies are often pulled down from external sources).

Thanks

**Comment by rynowak** [comment]
Closing this because we've turned this into a library for now. using https://github.com/dotnet/tye/issues/313 to track making this go away completely.
