### ISSUE TITLE
Extend Ingress feature

### ISSUE THREAD

**Issue by hbiarge** [dotnet/tye#358]
### What should we add or change to make your life better?
With the current implementation of the Ingress feature, Tye is not sending to the upstream service the path that is configured in the Ingress rule. This is OK and is a standard configuration in k8s environments where this path is stripped in the ingress controller (with the `nginx.ingress.kubernetes.io/rewrite-target` annotation for example with nginx ingress controller).
It would be nice if we can configure this behavior in the ingress rule to support sending this segment to the upstream service.

For example, if we have a service running in `localhost:5001` and an ingress running in `localhost:8080` with a rule configured for path '/service' to the service, right now a call to `http://localhost:8080/service/foo` is sent to `http://localhost:5001/foo`.
I would like to be able to configure the rule to forward the path segment also, so the same request to the ingress result in this call to the service `http://localhost:5001/service/foo`

This is something most proxies or load balancers do and we usually configure it in the ingress definition, so may be, it make sense to implement in Tye.

### Why is this important to you?
The scenario I would like to manage is when I have the same service exposed through two different ingresses, each one with a custom path. The application has logic to store that path in the request pipeline and apply custom logic depending of this value.

**Comment by davidfowl** [comment]
Yep this makes sense. I left it out for now.

**Comment by rynowak** [comment]
Thanks for the feedback. We plan to do this, and we're tracking this with #375
