### ISSUE TITLE
Dashboard enhancement

### ISSUE THREAD

**Issue by juanidamato** [dotnet/tye#382]
Hi,
When the source project  path is too long the horizontal scroll bar is so big.
I suggest to Include a class on site.css for this TD cell and modify your razor page to include this class.

.source-project-td
{
    word-break: break-all;
    min-width: 300px;  //Or any other value that you consider 
}
![before](https://user-images.githubusercontent.com/16365314/79642456-258d8b00-8163-11ea-9c96-aa9d32fe2fc1.png)
![after](https://user-images.githubusercontent.com/16365314/79642458-2aead580-8163-11ea-87c6-3c1ebcf45d62.png)

**Comment by davidfowl** [comment]
@juanidamato care to send a pull request?
