### ISSUE TITLE
Bring back build parallelism

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#389]
We had to remove build parallelism because MSBuild doesn't automatically coordinate builds of a project. Building a project multiple times at a time will usually cause sadness, and it was easy to trigger with Tye when you have a shared dependency project used by multiple services.

Some ideas about how to bring it back (discussed with @rainersigwald):

- Generate a project with p2ps to all of the things we want to build and invoke MSBuild on **that**
- Use `BuildManager` in memory and queue multiple builds 

The first one of these would probably be a big improvement because:

- Allows MSBuild to do its thing for parallelism
- Reduces the number of times we shell out and launch a new `dotnet` process

Doing the second one of these would be more work, but probably moves us in a direction we want to go eventually:

- We can reuse the state we already have in memory from evaluation
- We can eliminate shelling out completely

**Comment by davidfowl** [comment]
@rynowak putting this in 0.2.
