### ISSUE TITLE
Add support for building a docker container using dockerfile and context directory

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#394]
See: https://github.com/amarie401/tye-test-projects/issues/12

It's fairly common to need something like a node app, or static front-end app that's going to build with a dockerfile alongside a whole bunch of .net projects.

Adding support for building an image (like docker-compose) will unblock a whole lot more exploration as well as scenarios users have asked for.

**Comment by rynowak** [comment]
We should also doc this and add to our recipes docs

**Comment by jkotalik** [comment]
Still need to do work for `tye deploy`
