### ISSUE TITLE
tye generate places random chars at the start of the file 

### ISSUE THREAD

**Issue by brendandburns** [dotnet/tye#402]
### Describe the bug
the YAML file produced by `tye generate ...` has non-yaml characters at the beginning of the file

### To Reproduce
Go through the `deploy` tutorial
run `tye generate`
run `less <generated-yaml-file>`
See that the file has:
```
<U+FEFF>kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
```

### Further technical details

Version: 0.2.0-dev (HEAD on Github)
Platform: Linux (Ubuntu 18.04)
Dotnet: 3.1.201

**Comment by rynowak** [comment]
Can repro on mac as well. This is a UTF8 bom - which doesn't make a ton of sense on *nix. Most of the tools seem to accept this just fine. I'm not sure if visual studio will trip out without one 😢
