### ISSUE TITLE
Consider configuration options for connectionString bindings

### ISSUE THREAD

**Issue by spboyer** [dotnet/tye#427]
### What should we add or change to make your life better?
As a nice option in .NET Core we can bind appSettings to IOptions<T>, do Configuration.Bind etc., for sections and so on which may include the connectionString for databases, redis and external services.

When using the **connectionString** in tye.yaml, you are forced to change that pattern and/or make exceptions in your code for if/then/nulls to set these values.

Can we have a _targetSetting_ or _settingName_ to inject this value as a part of the binding to not break this?

**Comment by davidfowl** [comment]
I don't understand the problem. Can you show a code sample of what you have to change today and what code you would like to write after the change?

**Comment by spboyer** [comment]
Consider the settings here:

```
"MongoDB": {
    "Database": "TodoDB",
    "ConnectionString": "mongodb://root:example@localhost:27017"
  },
```

I can bind to a class using:

```
var config = new ServerConfig();
            Configuration.Bind(config);
```
class:
```
public class ServerConfig
    {
        public MongoDBConfig MongoDB { get; set; } = new MongoDBConfig();
    }

public class MongoDBConfig
    {
        public string Database { get; set; }
        public string ConnectionString { get; set; }
        }
    }
```

However, since the tye process creates a connectionStrings value.  

Previously I was injecting just the **MongoDBConfig** into the context, but now having to also send **IConfiguration** also. 

```
public TodoContext(MongoDBConfig config, IConfiguration configuration)
        {
            string conn = string.IsNullOrEmpty(config.ConnectionString) ? configuration.GetConnectionString("mongo") : config.ConnectionString;
          
            var client = new MongoClient(conn);
            _db = client.GetDatabase(config.Database);
        }
```

**Comment by davidfowl** [comment]
I think this feature is better solved by this:
- https://github.com/dotnet/tye/issues/377

The idea is to allow specifying aliases for bindings. You can have your own environment variables for   a binding. In this case MONGODB__CONNECTIONSTRING.

PS: The only difference here is that .NET Core has a different way to express connection strings that you aren't currently using. But yes, it does assume that you will be using the GetConnectionString method instead of the typical configuration binding.

**Comment by jkotalik** [comment]
Closing in favor of #377
