### ISSUE TITLE
Disable color in logs for deployed apps

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#434]
### Describe the bug

We pass an env-var to dotnet applications when doing `tye run` to disable colorization via ANSI escape codes for the console logger.

We don't do this today for deployed applications.

### To Reproduce

Deploy something, and look at the log output.

**Comment by QueenCitySmitty** [comment]
I'd like to take this it doesn't sound too bad.  I'm not really sure how to disable colorization in ``tye run`` though.. can you give me an example or walk me through it?  Relatively new to the space.

**Comment by rynowak** [comment]
The relevant code for `tye run` is [here](https://github.com/dotnet/tye/blob/master/src/Microsoft.Tye.Hosting/ProcessRunner.cs#L186). Basically the idea is that when we're generating dockerfiles or k8s manifests we could set this for deployed applications.

**Comment by QueenCitySmitty** [comment]
Where are the logs I should be looking at to validate?

**Comment by rynowak** [comment]
To validate, you'd need to deploy something and then get its logs with `kubectl logs svc/<name-of-service>` You should see logs that are uncolorized, and don't contain things like `ESC[31m`

**Comment by jkotalik** [comment]
FYI we don't run automated tests with kubernetes at the moment, so you'll need to manually verify this.

**Comment by QueenCitySmitty** [comment]
Np, I ran through the deployment examples the other day and they got me where I need to go for this.  Thanks!

**Comment by jkotalik** [comment]
@QueenCitySmitty did you get a chance to do this?

**Comment by QueenCitySmitty** [comment]
@jkotalik no, I've been really busy with all the Covid stuff.  I'd still like to do it though, I see you added it to the next sprint planning, is there any process I need to do?

**Comment by jkotalik** [comment]
No process whenever you get to it. It's mostly a reminder if you don't get to it for us to consider fixing it as well. However, we'll give you ample opportunity to try fixing it first 😄

**Comment by QueenCitySmitty** [comment]
Might still need direction, but I'll investigate tonight/this weekend.

**Comment by QueenCitySmitty** [comment]
Found a way to disable the color, I added:
```csharp
project.EnvironmentVariables.Add(new EnvironmentVariableBuilder("DOTNET_LOGGING__CONSOLE__DISABLECOLORS") { Value = "true" });
```
to DockerfileGenerator.cs in ``ApplyContainerDefaults`` after this line. https://github.com/dotnet/tye/blob/38c6717a6629ba2df4345835eb5da4a582b27f49/src/Microsoft.Tye.Core/DockerfileGenerator.cs#L126

I have it ready to PR, wanted to get some input first.  LMK what you think, if I get the thumbs up, I'll put out the PR.

**Comment by jkotalik** [comment]
That looks like the right spot IMO.

Did you get the chance to validate it as well?

**Comment by QueenCitySmitty** [comment]
Yeah I did, here's the before and after in PS: 

Before:
![image](https://user-images.githubusercontent.com/8077887/87326341-748b5800-c4e7-11ea-89df-e7a701247d80.png)

After:
![image](https://user-images.githubusercontent.com/8077887/87326357-7a813900-c4e7-11ea-89d4-73ed0d68e935.png)

Also verified in Terminal, colors don't appear anymore.
