### ISSUE TITLE
Unable to build tye from source in terminal: dotnet-install failed

### ISSUE THREAD

**Issue by NikiforovAll** [dotnet/tye#441]
When I  try to run `\.build.cmd -test` from PowerShell, I get next error:
![image](https://user-images.githubusercontent.com/8037439/81093560-f456de00-8f0a-11ea-94cb-eddb98e73198.png)

I might need to add NuGet source or something like that. Currently, it isn't documented, so it is not possible to follow [developer_guide.md](https://github.com/dotnet/tye/blob/master/docs/developer_guide.md)

```powershell
> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  752
> dotnet --version
3.1.102

```

**Comment by jkotalik** [comment]
Hm, odd I'm not hitting that when running it locally (before and after activating). It looks like it failed to install dotnet for some reason. Unfortunate there isn't an error produced.

Could you try a few things:

- Delete the .dotnet folder, build will regenerate it appropriately.
- Try running .\build.cmd without -test, just to make sure testing doesn't affect it.

**Comment by NikiforovAll** [comment]
Unfortunately, it doesn't help:

1. `rm .\.dotnet -Force -Recurse`
2. `.  .\activate.ps1`
3. `.\build.cmd`

Looks like it fails on _InstallDotNetCore_ Target.  
`.\build.cmd -v d`
Error message/log as gist: [error:/tye/issues-441](https://gist.github.com/NikiforovAll/817b2d51cb958a6883d595c5f61d2abb)

My uneducated guess, It might relate to https://github.com/dotnet/runtime/issues/34015

**Comment by jkotalik** [comment]
Yeah I don't think that issue is related. @dougbu @JunTaoLuo @wtgodbe any ideas?

**Comment by wtgodbe** [comment]
You shouldn't need to modify your nuget.config - I'm surprised to see this error from a clean installation. Looks like an Arcade issue w/ InstallDotNet - @chcosta @JohnTortugo have you seen it before?

**Comment by NikiforovAll** [comment]
It is certainly interesting for me to know what caused the issue. But, I ended up reinstalling VS Studio 2019 and installed [.vsconfig](https://github.com/dotnet/runtime/blob/master/.vsconfig). It solved the problem. Thank you, I appreciate your help.
