### ISSUE TITLE
Not detecting bindings in 2.1 project

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#445]
### Describe the bug

Tye is not detecting asp.net core in [these projects](https://github.com/SteeltoeOSS/Samples/blob/2.x/MusicStore/docker-compose.yml). The result is that no bindings are created

### To Reproduce

Ask @amarie401 xD

I suspect this reproduces with an asp.net core 2.1 project

**Comment by jkotalik** [comment]
Going to take a look at this.

**Comment by jkotalik** [comment]
I didn't see this reproduce when converting part of the voting app from 3.1 to 2.1. However, I did find some other issues along the way 😄 .

@amarie401 when you are debugging this app again in the future, pull me in so I can help debug what is going on.

**Comment by amarie401** [comment]
@jkotalik could you pull [this](https://github.com/amarie401/tye-test-projects/tree/master/steeltoe-oss) down and run tye in order to replicate the binding issue in the dashboard.

**Comment by amarie401** [comment]
Nvm...it's working now. Needed to update my version of Tye..whoops :P
