### ISSUE TITLE
Use tye in my integration test framework for microservices

### ISSUE THREAD

**Issue by brucezlata** [dotnet/tye#484]
Hi, I think the user scenario. To use tye in integration test framework for dotnet core microservices.
The requirements may be 
1) tye can microservice and its dependencies which are dotnet core apps (dll) in my local machine.
2) tye can start to run integration test which including cross services calling
3) tye can start emulation, for example, cosmos db, storage and etc.

And tye is Microsoft opensource project? When it will be released?

**Comment by brucezlata** [comment]
Also, can tye start microservice from dll, not only project file?

**Comment by davidfowl** [comment]
Do you want tye to run a test or just be part of the infrastructure for setting up a test?

> And tye is Microsoft opensource project? When it will be released?

https://github.com/dotnet/tye#current-status

**Comment by brucezlata** [comment]
use it as a port of  the infrastructure for setting up a test, helping to start service and its dependencies locally. That's best to integrate to CI, if could.

**Comment by glennc** [comment]
So you want to use Tye to spin up all the pieces, then run a test against them all, then shut everything down?

**Comment by jkotalik** [comment]
https://github.com/dotnet/tye/issues/47 ?

**Comment by brucezlata** [comment]
> So you want to use Tye to spin up all the pieces, then run a test against them all, then shut everything down?

True. Also think, need a way to startup hook. It will help for testing.

**Comment by brucezlata** [comment]
> #47 ?
Yes.

**Comment by jkotalik** [comment]
Closing as dup.
