### ISSUE TITLE
Detect Current Service Endpoint

### ISSUE THREAD

**Issue by quoctuancqt** [dotnet/tye#492]
Using the frontend-backend example.

Is there any solution to do like that:

![image](https://user-images.githubusercontent.com/26458668/82655884-0ba50380-9c4d-11ea-885b-835c7a2449ea.png)

This seems like it doesn't work.

![image](https://user-images.githubusercontent.com/26458668/82656060-4c9d1800-9c4d-11ea-851e-85f9f7f9aace.png)

**Comment by davidfowl** [comment]
Are you running the project with tye?

**Comment by quoctuancqt** [comment]
> Are you running the project with tye?

Yes, I’m using frontend-backend example and modified like the picture

**Comment by davidfowl** [comment]
So you modified which project? The backend to get the backend address?

**Comment by davidfowl** [comment]
@jkotalik did you dependencies change maybe break this? 

@quoctuancqt why are you trying to detect your own address? Do you have a scenario?

**Comment by quoctuancqt** [comment]
> So you modified which project? The backend to get the backend address?

Yes, corect

**Comment by quoctuancqt** [comment]
> @jkotalik did you dependencies change maybe break this?
> 
> @quoctuancqt why are you trying to detect your own address? Do you have a scenario?

Assume backend is my Web API which I have implement a middleware to handle Authorization using JWT. That’s why I need to resolve my own address.

**Comment by jkotalik** [comment]
@quoctuancqt this should be fixed in 0.3. Feel free to try the latest nightlies to confirm it works.

**Comment by quoctuancqt** [comment]
> @quoctuancqt this should be fixed in 0.3. Feel free to try the latest nightlies to confirm it works.

I try with tye version 0.3 but it still doesn't work.
