### ISSUE TITLE
watch project changes

### ISSUE THREAD

**Issue by alefcarlos** [dotnet/tye#499]
### What should we add or change to make your life better?

It would be cool if we had hot reload, like `dotnet watch run` when dependency type is `project`

### Why is this important to you?

It is because it is easier to make changes on the fly. I always use `donet watch` when  running applications.

**Comment by cvalerio** [comment]
I agree, since tye is a development tool it should allow to reload a specific project at runtime (via dashboard) or leverage `dotnet watch run`, maybe with a switch option at `tye run` command.

**Comment by jkotalik** [comment]
I opened a PR that allows passing `--watch` to tye. This will call `dotnet watch run` on all projects. I'd appreciate any feedback on it.

**Comment by jkotalik** [comment]
This is now merged. Would appreciate people trying the nightlies to double check as we'd like to make a release of tye this week 😄

**Comment by alefcarlos** [comment]
I'm gonna try it!

**Comment by myty** [comment]
@jkotalik Adding `--watch` to tye run is definitely picking up file changes and rebuilding the project, so 👍 for that, however it doesn't seem to pick up the change until I actually shutdown tye and start it backup again.  Do I need to do something different with the yaml file maybe? https://github.com/myty/openbrewerydb-graphql-dotnet/blob/feature/dockerize/tye.yaml

**Comment by jkotalik** [comment]
> however it doesn't seem to pick up the change until I actually shutdown tye and start it backup again. Do I need to do something different with the yaml file maybe?

Can you clarify what this means? If you need to shutdown tye and start it again, it makes me think it's not working.

**Comment by myty** [comment]
Yeah, It's definitely rebuilding when the files changes, but I have a feeling it's not updating the container maybe? Not sure exactly 😄

**Comment by jkotalik** [comment]
Ah, that may be a scenario that needs to be updated. I'll look into that.

**Comment by myty** [comment]
Awesome. Thank you!

By the way, keep up the great work. Really liking the vision and direction of this project.

**Comment by cveld** [comment]
@jkotalik With `tye run --watch`, whenever I change a file, the full dotnet project is rebuilt which disconnects the Blazor Server websocket connection. Any clue what I can do to circumvent this? 

```
tye --version
0.11.0-alpha.22111.1+3edef5428949c518c078844d6438e5ba86fce600
```

```
dotnet --version
6.0.202
```
