### ISSUE TITLE
How to set image imagePullSecrets?

### ISSUE THREAD

**Issue by MikyChow** [dotnet/tye#508]
How to set image imagePullSecrets?

**Comment by jkotalik** [comment]
I don't think we currently support this. To make sure, you are referring to the imagePullSecrets to set a secrety for the registry? I see [this](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) and [this](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod) as my context.

**Comment by MikyChow** [comment]
Thx. we currently use helm create chart deploy, we want try tye.

**Comment by jkotalik** [comment]
This currently isn't at the top of our priority, but we would accept a contribution for it.

**Comment by jongio** [comment]
This is needed to connect to ACR from k8s cluster
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes#use-the-image-pull-secret

Without this, I believe we are blocked on using docker-desktop/k8s with ACR

azsdke2e

**Comment by chrisjust** [comment]
Is anyone working on this? 

Otherwise I might be able to toss some hours at it 😃

**Comment by chrisjust** [comment]
Seems noone's working on this. 

Where'd you invision this property being, on the service or as a root level option?

I invision having it at the service level. 

And that it'd only reference an existing secret - so Tye doesn't create the secret aswell.

**Comment by jongio** [comment]
@jkotalik can chime in, but I would like the flexibility to specify:

1. imagePullSecret for individual services, so I can pull from various authenticated registries
1. imagePullSecret for the whole project, so I can easily set it in once place in tye.yaml and tye converts that to imagePullSecret for each pod/deployment.

**Comment by jkotalik** [comment]
@jongio do you think we need to also be able to specify a registry per service?

**Comment by jongio** [comment]
Yeah, for full flexibility, but not require it

Have one global at the root and then allow each service to overide both registery and pull secret.

**Comment by stefankip** [comment]
I would love this as well. Currently trying to create a build locally with the PR included.
