### ISSUE TITLE
Don't use ":" in the configuration name

### ISSUE THREAD

**Issue by mastoj** [dotnet/tye#509]
":" is not valid in environment key names in ubuntu, so if one want to use Tye for local dev but deal with production deployment using something else it is hard (impossible) to override the config in bash. This is for the code here: https://github.com/dotnet/tye/blob/083a97f353069ef8a091651d4c9ca445c994b2e5/src/Microsoft.Tye.Extensions.Configuration/TyeConfigurationExtensions.cs#L15

Or is it something that I'm missing? Ideally I would like to set an environment variable in production that is used when referencing another service.

**Comment by TimHess** [comment]
That code is operating on [IConfiguration keys](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#configuration-keys-and-values), not raw environment variables

**Comment by mastoj** [comment]
But I think you can sen values in IConfiguration using environment variables, at least that worked when I tested.

**Comment by TimHess** [comment]
From the link I included earlier:

> Hierarchical keys
> Within the Configuration API, a colon separator (`:`) works on all platforms.
> In environment variables, a colon separator may not work on all platforms. A double underscore, `__`, is supported by all platforms and is automatically converted into a colon `:`.

So you could use `service__{key}__host` to set an environment variable, but you will always use `service:{key}:host` to read it because that's how IConfiguration works

**Comment by mastoj** [comment]
Got it, will try it out.

**Comment by glennc** [comment]
Right the config system can handle `:` or `__` in environment variable names. In code you always use `:`. See examples here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables

**Comment by glennc** [comment]
Drop a comment and we will close this if everything is good :).

**Comment by mastoj** [comment]
Worked as described @glennc. I did try it before but I guess I missed on underscore or something.
