### ISSUE TITLE
Pass build arguments into docker build step when using a yaml file

### ISSUE THREAD

**Issue by ossentoo** [dotnet/tye#511]
Hi,

My application pulls private nuget packages from an Azure DevOps feed in the docker image build.  We normally accomplish this in our Azure DevOps pipeline by passing a build argument to docker build.

I've setup a yaml file to run locally at the moment. This is failing during the dotnet restore step in the Dockerfile as expected, because it needs the credential to the private nuget feed.

Is there a way of passing this in? I'm running locally so, I don't mine passing the PAT in somehow.

I've tried this:

name: application
services:
- name: web
  dockerFile: ../application-web/src/Dockerfile --build-arg PAT=***

I get this output when running tye run with a tye.yaml file in the same directory:

[06:44:57 INF] Building docker image web from docker file
[06:44:57 INF] [web]:unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/blah/application-web/src/Dockerfile --build-arg PAT=***: no such file or directory

**Comment by jkotalik** [comment]
Yeah, today passing in `dockerFile` assumes that it is only a path to the docker file, and doesn't include args.

@davidfowl for `docker run`, do we allow passing in args as well? Is that through the `args` section in the yaml?

**Comment by ossentoo** [comment]
Ok.

Is there any work around for now?  Can I call docker build for example for now?

**Comment by davidfowl** [comment]
I thought we had support for arguments being passed to build but there isn't we'll need to add it.

**Comment by ossentoo** [comment]
I'm going to work on a PR for this issue
