### ISSUE TITLE
Avoid locking .NET exe/dlls, monitor them for changes instead

### ISSUE THREAD

**Issue by ashmind** [dotnet/tye#515]
### What should we add or change to make your life better?

I think Tye should make a copy of project binaries instead of locking them in place, and should monitor and update/restart that copy if binaries change.

This is not the same as #499 -- having both this and #499 as an option would be the best. For certain kinds of major refactoring work watch might be too intensive and manually timed builds work better, for other kinds of work watch is perfect.

### Why is this important to you?

This will make local development experience nicer and more straightforward.
Currently I need to stop Tye to build a new version.

**Comment by davidfowl** [comment]
I don’t get why you’d bed this for local dev vs #499? What’s the development scenario where you don’t change source?

**Comment by ashmind** [comment]
There are development scenarios when I change source too much and too quickly and don't want the overhead/waste of the background compilation on every small change that is guaranteed to fail anyways (as I know more changes are still in progress).

I also want to see the errors/etc in normal VS environment so it's easier to fix them, so I will run the manual build either way for those changes.

**Comment by davidfowl** [comment]
That sounds like you want the tool to debounce changes or have an explicit way to trigger a build. I’m not seeing how it relates to this request and as it currently stands we’re not likely to implement it.

**Comment by ashmind** [comment]
I don't really want an explicit way to trigger the build _within_ the tool, as I will not be able to react to the errors as well as I can when they are shown in VS. However I do see your point. If VS integration of `dotnet watch` gets better I think #499 would be enough.

**Comment by jkotalik** [comment]
We are going to add watch via https://github.com/dotnet/tye/pull/526. We are going to close this issue for now as we believe watch should cover most of the scenarios.
