### ISSUE TITLE
Tye undeplo is not working

### ISSUE THREAD

**Issue by NileshGule** [dotnet/tye#518]
### Describe the bug
I have deployed an application using Tye deploy successfully. When I run the Tye undeploy command it fails to undeploy the resources which were deployed to an AKS cluster. I can list the pods which are running using kubectl get pods command

### To Reproduce
Deploy an application services using Tye deploy command

Run Tye Undeploy command. **Tye shows Found 0 resource(s)**

### Further technical details

tye version : 0.3.0-alpha.20273.1+65c09d737e36edd3757b248967db252a7fff9e75
- If possible rerun the command with `-v debug`
<img width="1119" alt="tye pod part of" src="https://user-images.githubusercontent.com/1298374/83327512-11cf5b80-a2af-11ea-8ed6-76eded50a5e9.PNG">
<img width="719" alt="tye undeploy no resources found" src="https://user-images.githubusercontent.com/1298374/83327513-13991f00-a2af-11ea-8452-50d2ae885959.PNG">
<img width="816" alt="tye deploy running pods" src="https://user-images.githubusercontent.com/1298374/83327516-1562e280-a2af-11ea-8ca5-95c8bdc84994.PNG">

 and include the output
- The platform Windows 10

**Comment by davidfowl** [comment]
@jkotalik Did you try undeploy with dockerfile built containers?

**Comment by NileshGule** [comment]
@jkotalik you can find the repo on which I am trying Tye currently here
https://github.com/nileshgule/pd-tech-fest-2019

**Comment by jkotalik** [comment]
Yeah sounds like that is most likely the issue.

**Comment by jkotalik** [comment]
@NileshGule I think the bug is a bit on both sides here. The issue is that there is no application name defined in the tye.yaml. I see a few actions here:
1. Default to the application name, if not defined, to the current directory name.
2. Required that a name is defined in the tye.yaml.

@davidfowl thoughts?

**Comment by NileshGule** [comment]
hi @jkotalik,
It would be better to keep the deploy & undeploy commands in sync. If the tye deploy is able to deploy the application without specifying the application name, then undeploy can use the same convention used while deploying the application to reverse the action.

Other option could be to make the application name mandatory.

**Comment by jkotalik** [comment]
@NileshGule I fixed it and did the first option you suggested.

**Comment by jkotalik** [comment]
Feel free to try the latest nightly build and see if that works.
