### ISSUE TITLE
Deploying to Kubernetes ~ WOWWW

### ISSUE THREAD

**Issue by ClueeZhuo** [dotnet/tye#524]
# I successfully deployed to K8S according to the example of the official blog.(https://devblogs.microsoft.com/aspnet/introducing-project-tye/)

![image](http://i2.tiimg.com/635339/344f1162dadaa44d.png)

# kubectl port-forward svc/frontend 5000:80

# BUTTT  navigate to http://localhost:5000 An exception occurred

![image](http://i2.tiimg.com/635339/2fa142407e943008.png)

Error.
An error occurred while processing your request.
Request ID: |9ad50a3d-4bc112731f250b84.

Development Mode
Swapping to the Development environment displays detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

**Brothers, come and helppp**

**Comment by glennc** [comment]
This looks there is an error in your app, you should be able to see more details in the logs of the service. Can you check on the logs for frontend and see what they say?

**Comment by ClueeZhuo** [comment]
AHAAAAAAAAAA

I solved my problem~~~

`binding-production-redis-secret` has error , fix it then redeploy~~~ that problem is be solved
