### ISSUE TITLE
Development only services?

### ISSUE THREAD

**Issue by onionhammer** [dotnet/tye#541]
I know there are `external` and `executable` services, what if I want to run a SQL database locally but use Azure SQL when deployed? How would I set up the configuration to run a SQL database only locally and not deployed?

**Comment by jkotalik** [comment]
How would you like to run the SQL database locally? If you running it inside of a container, for example running https://hub.docker.com/_/microsoft-mssql-server, you can have an image reference inside of your tye.yaml to it.

When you deploy, tye doesn't deploy image references, only .NET projects or references to local Dockerfiles. So the SQL database image won't be deployed; you'll need to provide a connection string for the SQL database, which can be your Azure SQL.

The voting sample has an example of using postgressql: https://github.com/dotnet/tye/tree/master/samples/voting

Going back to the original ask though, I think being able to specify environments (like development, production, etc) could be another way to approach this.

**Comment by onionhammer** [comment]
Ahh sounds like it was just an understanding on my part; I assumed that any service other than 'externa' or 'executable' would be deployed, now I see that 'image' services are *also* not deployed, so that alone seems to address my concern.

I think perhaps we can close this issue, but I love your idea of specifying different environments somehow - as a separate idea from my dumb question :)

**Comment by jkotalik** [comment]
Yeah, we have an issue for different ENVs here: https://github.com/dotnet/tye/issues/413
