### ISSUE TITLE
Tye env-vars for .net microservice

### ISSUE THREAD

**Issue by sasanknvs** [dotnet/tye#545]
Hi all,

I am trying to do Tye run against my microservice project which is targeting .netcore 2.1.
It goes on running forever with the error "No process selected with process id: 4520". And then it is trying to select another process with a different process id and same error occurs.I could see the logs on the command prompt but the service is not running successfully.  

In the logs I found that application is not able to read environment variables from launch settings.json. Is there a way we can specify environment variable in the Yaml manifest file

**Comment by jkotalik** [comment]
I'll take a look into this.

**Comment by jkotalik** [comment]
Sorry, I re-read the issue. A few things.

Right now, settings in launchsettings.json are not used in tye; they must be set in the tye.yaml. You can set environment variables via: https://github.com/dotnet/tye/blob/master/docs/reference/schema.md#environment-variables

**Comment by jkotalik** [comment]
Going to close for now, feel free to reopen.
