### ISSUE TITLE
Drats! 'deploy' failed:         Cannot apply manifests because kubectl is not installed.

### ISSUE THREAD

**Issue by bbteam17** [dotnet/tye#559]
Hi  I am try   test tye  on  env.  
I am using  ubuntu 18.04  on vmware. 
and  install microk8s  on it.  
using  alias  for kubectl  
` alias kubectl='microk8s kubectl'` in  $HOME/.bashrc
try your  this  article  https://devblogs.microsoft.com/aspnet/introducing-project-tye/.
when I try  that:
 `tye deploy -i
Loading Application Details...
Drats! 'deploy' failed:
	Cannot apply manifests because kubectl is not installed.
`
I checked this error  where come from .   its come from where  tye try check kubectl version and  cluster-info.
when I try  on terminal  below command  , I can get  below response

`microk8s kubectl cluster-info
Kubernetes master is running at https://127.0.0.1:16443
CoreDNS is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.`

and I can get kubectl version too. 
`kubectl version --short
Client Version: v1.18.4-1+6f17be3f1fd54a
Server Version: v1.18.4-1+6f17be3f1fd54a
`

![image](https://user-images.githubusercontent.com/32478068/85800075-9e4f2b80-b740-11ea-8dfd-4c0496fe1694.png)

**Comment by jkotalik** [comment]
Interesting, my gut says when running kubectl in tye, the alias isn't being picked up. Can you try running `tye deploy -i -v Debug` and see if you get more output?

I think we may need to provide a recipe for using minikube with tye. I see this being an adoption blocker if this currently doesnt' work.

**Comment by bbteam17** [comment]
` tye deploy -i -v Debug` 
Loading Application Details...
Locating .NET SDK...
Found .NET SDK at: /usr/share/dotnet/sdk/3.1.301/
Registered .NET SDK.Loading project '/home/tlax/tlaxNetCore/tye/microservice/backend\backend.csproj'.
Loaded project '/home/tlax/tlaxNetCore/tye/microservice/backend\backend.csproj'.
Restoring project '/home/tlax/tlaxNetCore/tye/microservice/backend\backend.csproj'.
Build started 6/26/2020 9:16:50 AM.
__________________________________________________
Project "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" (Restore target(s)):

Target _FilterRestoreGraphProjectInputItems:
    __________________________________________________
    Project "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" is building "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" (_IsProjectRestoreSupported target(s)):

Target _GetAllRestoreProjectPathItems:
    Determining projects to restore...
    __________________________________________________
    Project "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" is building "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" (_GenerateRestoreProjectPathWalk target(s)):

    __________________________________________________
    Project "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" is building "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" (_IsProjectRestoreSupported target(s)):

Target _GenerateRestoreGraph:
    __________________________________________________
    Project "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" is building "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" (_GenerateRestoreGraphProjectEntry target(s)):

    __________________________________________________
    Project "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" is building "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" (_GenerateProjectRestoreGraph target(s)):

Target Restore:
    Committing restore...
    Assets file has not changed. Skipping assets file writing. Path: /home/tlax/tlaxNetCore/tye/microservice/backend/obj/project.assets.json
    Restored /home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj (in 85 ms).

    NuGet Config files used:
        /home/tlax/.nuget/NuGet/NuGet.Config

    Feeds used:
        https://api.nuget.org/v3/index.json
    All projects are up-to-date for restore.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.75
Restored project '/home/tlax/tlaxNetCore/tye/microservice/backend\backend.csproj'.
Build started 6/26/2020 9:16:51 AM.
__________________________________________________
Project "/home/tlax/tlaxNetCore/tye/microservice/backend/backend.csproj" (ResolveReferences;ResolvePackageDependenciesDesignTime;PrepareResources;GetAssemblyAttributes target(s)):


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.40
Found application version: 1.0.0
RunCommand=/home/tlax/tlaxNetCore/tye/microservice/backend/bin/Debug/netcoreapp3.1/backend
RunArguments=
TargetPath=/home/tlax/tlaxNetCore/tye/microservice/backend/bin/Debug/netcoreapp3.1/backend.dll
PublishDir=bin\Debug\netcoreapp3.1\publish\
AssemblyName=backend
IntermediateOutputPath=obj\Debug\netcoreapp3.1\
Found target framework: netcoreapp3.1
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 1838.5675ms
Loading project '/home/tlax/tlaxNetCore/tye/microservice/frontend\frontend.csproj'.
Loaded project '/home/tlax/tlaxNetCore/tye/microservice/frontend\frontend.csproj'.
Restoring project '/home/tlax/tlaxNetCore/tye/microservice/frontend\frontend.csproj'.
Build started 6/26/2020 9:16:52 AM.
__________________________________________________
Project "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" (Restore target(s)):

Target _FilterRestoreGraphProjectInputItems:
    __________________________________________________
    Project "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" is building "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" (_IsProjectRestoreSupported target(s)):

Target _GetAllRestoreProjectPathItems:
    Determining projects to restore...
    __________________________________________________
    Project "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" is building "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" (_GenerateRestoreProjectPathWalk target(s)):

    __________________________________________________
    Project "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" is building "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" (_IsProjectRestoreSupported target(s)):

Target _GenerateRestoreGraph:
    __________________________________________________
    Project "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" is building "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" (_GenerateRestoreGraphProjectEntry target(s)):

    __________________________________________________
    Project "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" is building "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" (_GenerateProjectRestoreGraph target(s)):

Target Restore:
    Committing restore...
    Assets file has not changed. Skipping assets file writing. Path: /home/tlax/tlaxNetCore/tye/microservice/frontend/obj/project.assets.json
    Restored /home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj (in 1 ms).

    NuGet Config files used:
        /home/tlax/.nuget/NuGet/NuGet.Config

    Feeds used:
        https://api.nuget.org/v3/index.json
    All projects are up-to-date for restore.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.11
Restored project '/home/tlax/tlaxNetCore/tye/microservice/frontend\frontend.csproj'.
Build started 6/26/2020 9:16:52 AM.
__________________________________________________
Project "/home/tlax/tlaxNetCore/tye/microservice/frontend/frontend.csproj" (ResolveReferences;ResolvePackageDependenciesDesignTime;PrepareResources;GetAssemblyAttributes target(s)):


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.18
Found application version: 1.0.0
RunCommand=/home/tlax/tlaxNetCore/tye/microservice/frontend/bin/Debug/netcoreapp3.1/frontend
RunArguments=
TargetPath=/home/tlax/tlaxNetCore/tye/microservice/frontend/bin/Debug/netcoreapp3.1/frontend.dll
PublishDir=bin\Debug\netcoreapp3.1\publish\
AssemblyName=frontend
IntermediateOutputPath=obj\Debug\netcoreapp3.1\
Found target framework: netcoreapp3.1
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 705.4078ms
**Drats! 'deploy' failed:
        Cannot apply manifests because kubectl is not installed.**

**Comment by bbteam17** [comment]
I tried  install another ubuntu vm machine with same config just install minikube  .    it is working  as well.

**Comment by jkotalik** [comment]
> I tried install another ubuntu vm machine with same config just install minikube . it is working as well.

To clarify, when you say it is working well, does that mean tye is working on the VM there?

Again I think we need a recipe for Minikube + tye as a verification measure.

**Comment by bbteam17** [comment]
ok.   its working with minikube as expected .  but it is not working with microk8s. Because microk8s using kubctl internal  commans like "microk8s.kubectl.... "  and tye check kubernates version or cluster info like defaul command "kubectl version or kubectl cluster-info" then throw above exception. As you said above  tye could not use alias  what i set  alias kubectl= microk8s. kubectl". if you prepare "how to use tye with microk8s" it will be usefull for us. thx+regards

**Comment by bbteam17** [comment]
sorry for late answer in here ,   my problem resolve after  below code execute . because tye use  host's kubectl . 

https://microk8s.io/docs/working-with-kubectl
`
cd $HOME`
`mkdir .kube`
`cd .kube`
`microk8s config > config`

![image](https://user-images.githubusercontent.com/32478068/90416220-7c27b900-e0b2-11ea-879a-e1439ba39154.png)

**Comment by tebeco** [comment]
you can try to use `kubeconfig` env var to point to a specific configuration folder

that's probably something you could re-use

I hope `minikube` support that as a standard too

**Comment by bbteam17** [comment]
Hi tebeco,
 my env is  using Microk8s (https://microk8s.io/)  .   I dont use minikube ,  when I tried  tye with minikube on other wsl2 distro,   there was  no problem .
