### ISSUE TITLE
Support podman based distributions

### ISSUE THREAD

**Issue by tmds** [dotnet/tye#563]
Distributions like Fedora, Red Hat Enterprise Linux provide `podman` instead of `docker`.

`podman` has high compatibility with `docker` but the implementation is different. `podman` doesn't have a daemon that runs as `root`. This allows regular users to launch containers without elevating their privileges.

It would be nice if `tye` supports `podman` based distributions and is able to work in a rootless mode. (The network creation currently performed by `tye` requires root.)

I can help implement this.

cc @davidfowl

**Comment by davidfowl** [comment]
I think this makes sense to do. We need to figure out what to do about some of the options in the tye.yaml. They have the name docker 😄. I'm also interested to see how compatible the APIs are (I know what podman is but I haven't looked deeply enough to understand the differences). Maybe throw up a draft PR with the implementation so we can learn more and then we can iterate from there.
