### ISSUE TITLE
tye rewrite Dapr Environment variable

### ISSUE THREAD

**Issue by rspaulino** [dotnet/tye#575]
I'm using tye locally(tye run) to Run Dapr locally as well and use service to service invocation from Dapr.

`$"http://localhost:{Environment.GetEnvironmentVariable("DAPR_HTTP_PORT")}/v1.0/invoke/backend/method/"`

this work running when using dapr run or deploy to k8s. I wrote a method to print all environment variable to see why when using tye is coming empty and it look like tye is rewriting the environment variable. 

`$"http://localhost:{Environment.GetEnvironmentVariable("SERVICE__FRONTEND-DAPR__HTTP__PORT")}/v1.0/invoke/backend/method/"`

and this is the output of the Environment variable from tye local:

```
[frontend_e61771b1-9]: SERVICE__BACKEND-DAPR__HTTP__HOST = localhost
[frontend_e61771b1-9]: SERVICE__FRONTEND-DAPR__HTTP__HOST = localhost
[frontend_e61771b1-9]: BACKEND-DAPR_METRICS_SERVICE_HOST = localhost
[frontend_e61771b1-9]: BACKEND-DAPR_METRICS_SERVICE_PROTOCOL = http
[frontend_e61771b1-9]: SERVICE__FRONTEND__HTTPS__PROTOCOL = https
[frontend_e61771b1-9]: SHLVL = 1
[frontend_e61771b1-9]: FRONTEND_HTTPS_SERVICE_PROTOCOL = https
[frontend_e61771b1-9]: SERVICE__BACKEND-DAPR__METRICS__PROTOCOL = http
[frontend_e61771b1-9]: __CF_USER_TEXT_ENCODING = 0x1F5:0x0:0x0
[frontend_e61771b1-9]: FRONTEND-DAPR_HTTP_SERVICE_PROTOCOL = http
[frontend_e61771b1-9]: SERVICE__BACKEND__PROTOCOL = http
[frontend_e61771b1-9]: SERVICE__BACKEND-DAPR__GRPC__PORT = 53423
[frontend_e61771b1-9]: BACKEND_HTTPS_SERVICE_PORT = 53419
[frontend_e61771b1-9]: BACKEND_HTTPS_SERVICE_HOST = localhost
[frontend_e61771b1-9]: SERVICE__FRONTEND__HOST = localhost
[frontend_e61771b1-9]: TERM_SESSION_ID = 147A436C-43F2-48DB-AE05-1CAE65830EBC
[frontend_e61771b1-9]: FRONTEND-DAPR_METRICS_SERVICE_PORT = 53422
[frontend_e61771b1-9]: SERVICE__BACKEND__PORT = 53418
[frontend_e61771b1-9]: FRONTEND-DAPR_METRICS_SERVICE_PROTOCOL = http
[frontend_e61771b1-9]: BACKEND-DAPR_METRICS_SERVICE_PORT = 53425
```
I know on pull request #510 it mention that it's fixed, it's injecting the variables but by changing the name it mean that the isn't as portable as it could be.

Any suggestion, would be gladly appreciated.

**Comment by jkotalik** [comment]
I'm a little confused on what the issue you are hitting is. Can you clarify what the issue is again?

**Comment by rspaulino** [comment]
Sure,

The following code return a **port number** when run **dapr CLI**
```C#
Environment.GetEnvironmentVariable("DAPR_HTTP_PORT")
```

But when I run the same project with Tye the same code doesn't return anything and I have the extension added too.

```yaml
name: dapr.microservices
extensions:
- name: dapr
  log-level: debug
```

let me know if it's clear now. thanks

**Comment by rspaulino** [comment]
Hi @jkotalik 

I know it been a while since you edit this code but I think I found the problem, I don't know if there is a specific reason on why only `daprGrpcPort` was added with `project.EnvironmentVariables.Add` but this add the proper environment variable name `DAPR_GRPC_PORT`

https://github.com/dotnet/tye/blob/c60541ba96c6b8eb23d185bce860369156542a29/src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs#L136

Unlike 
https://github.com/dotnet/tye/blob/c60541ba96c6b8eb23d185bce860369156542a29/src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs#L126

This generate the following environment names:
`FRONTEND-DAPR_GRPC_SERVICE_PORT `
`SERVICE__FRONTEND-DAPR__GRPC__PORT`

**Comment by rynowak** [comment]
I think the problem here is that setting `DAPR_HTTP_PORT` is a behavior of the Dapr CLI. We don't use the Dapr CLI to launch in Tye, we use `daprd` directly once the app is already started.

We should do this in the Tye extension for Dapr so it's consistent.

**Comment by rynowak** [comment]
PR sent for this

**Comment by rynowak** [comment]
This should be fixed now in nightly builds - the issue is that Tye wasn't setting `DAPR_HTTP_PORT`.
