### ISSUE TITLE
Continuous reload of apps when changed

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/tye#609]
### What should we add or change to make your life better?

Like with a dev server for the web, continuously reload apps when they have been recompiled.
Integrate with Visual Studio and debug.

Make a change, recompile, and the app restarts in Tye.

### Why is this important to you?

It would simplify the development flow.

**Comment by jkotalik** [comment]
Have you tried `tye run --watch`? https://github.com/dotnet/tye/blob/e7cb54b801d62a1be15f2b14a41ea7d7159efe81/docs/reference/commandline/tye-run.md#options

**Comment by robertsundstrom** [comment]
> Have you tried `tye run --watch`? https://github.com/dotnet/tye/blob/e7cb54b801d62a1be15f2b14a41ea7d7159efe81/docs/reference/commandline/tye-run.md#options

No. Thanks! I will try.

**Comment by glennc** [comment]
Closing since I think --watch is what you needed :).
