### ISSUE TITLE
Project reference misspelling causes bad error message

### ISSUE THREAD

**Issue by jkears** [dotnet/tye#620]
Yesterday I was able to run Tye without any issues. 

Today when I type Tye run in the solution folder it returns **"Drats! 'run' failed: Failed to find dotnet. Make sure the .NET SDK is installed and on the PATH."**

Dotnet is in the path and executes as per the following screen shot..
 
![image](https://user-images.githubusercontent.com/1290937/89544795-8acbc180-d7d0-11ea-93cc-ce47b81bed0f.png)

The platform is Windows 10, 
The dotnet --version =>  3.1.302

**Comment by jkears** [comment]
I ran the upgrade and still the same issue prevails.

**Comment by jkears** [comment]
Solved ... but it is still a bug from my perspective ...

A project reference was miss-spelt... the error should say can't resolve project reference.

**Comment by ckadluba** [comment]
To be precise, this only happens if the path containing the project file is wrong. If the the path is correct but only filename of the project is misspelled, a useful error message is generated.
