### ISSUE TITLE
Running Azure Functions with Tye should not require installing Node/NPM

### ISSUE THREAD

**Issue by danroth27** [dotnet/tye#625]
Tye handles Azure Functions projects using the Functions Core Tools. Currently Tye assumes that the Functions Core Tools were installed using NPM, but the Functions Core Tools can be [installed using a standalone installer](https://docs.microsoft.com/azure/azure-functions/functions-run-local#install-the-azure-functions-core-tools). There's also work to support acquiring the Functions Core Tools as a .NET tool that could be installed globally or locally. Tye should support these other patterns so that installing Node/NPM isn't required.

**Comment by UmairB** [comment]
Problematic for me too since I use nvm to manage my node installations, and due to this I don't have a "npm" folder in my appData directory :(
