### ISSUE TITLE
multi-target projects  

### ISSUE THREAD

**Issue by 3GDXC** [dotnet/tye#648]
currently tye run fails when trying to run projects that are multi targeted
please consider supporting multi targeted projects or providing an option 
at command line to run a specified target

**Comment by tebeco** [comment]
@jkotalik sorry to ping you again on that one but may be this PR would help on that ?
Is there anything left to add to it ?

https://github.com/dotnet/tye/pull/567

**Comment by 3GDXC** [comment]
@tebeco thanks for pointing this out; I didn't see this.  Q: would tye default to the most current target for a project if no TargetFramework was specified ?

**Comment by tebeco** [comment]
I can tell for the "order of preference"
All I can say is that as a workaround you can specify explicitly the `TargetFramework` as a `buildProperty` in the YAML
that will somehow "bypass" the current issue.

The PR would just enable developper to do `tye run --framework netcoreappFOO.BAR`
