### ISSUE TITLE
Cannot Build tye after updating VS2019 16.8 preview3.0 / sdk 5.0.0-rc1 / VsCode (Lots of PackageReference are not loaded anymore)

### ISSUE THREAD

**Issue by tebeco** [dotnet/tye#660]
### Describe the bug
As I was rebasing a PR and trying to fix a review comment on it, it seems that I can't use either VS2019 16.8 Preview 3.0 or VsCode (Insider) anymore
Lots of `PackageReference` are not visible in the dependency tree
Most of the errors are "Unknown class / namespace"
This picture is only a small part of all the errors
![image](https://user-images.githubusercontent.com/2266487/93272096-0dbf3f00-f7b5-11ea-8ac7-ff785e96cec5.png)

### To Reproduce
same on `master/main` branch
```pwsh
git clone https://github.com/dotnet/tye
checkout 
dotnet tool restore
./restore.cmd
./build.cmd
./startvs.cmd
```

Note that all of this works: 
* `build.cmd`
* `./eng/common/build.ps1 -build`
* `./eng/common/build.ps1 -test`

### Further technical details
- The platform : Windows
- dotnet --info:
```
C:\dev\github\tebeco\tye   multiple-target-frameworks ≣ 
[00:43]❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20211
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  2.1.809 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
 C:\dev\github\tebeco\tye   multiple-target-frameworks ≣ 
```

**Comment by tebeco** [comment]
VsCode :
![image](https://user-images.githubusercontent.com/2266487/93274433-a5735c00-f7ba-11ea-82e4-10f9d9d201ac.png)

**Comment by jkotalik** [comment]
@JunTaoLuo any idea what could be going on here?

**Comment by tebeco** [comment]
### MOAR info:
"in case of doubt, try to build Signalr"
I almost managed to get (on `release/v5.0-rc1` > `restore.cmd; build.cmd; cd src/signalr` > `startvs.cmd` build
![image](https://user-images.githubusercontent.com/2266487/93275721-f5075700-f7bd-11ea-952d-4b1f6a5a61a4.png)
probably unrelated

**Comment by tebeco** [comment]
I manually edited a `csproj` in `dotnet/tye` and SOME part of the tree now appear, but that's all, still IDE glitch / can't build

![image](https://user-images.githubusercontent.com/2266487/93275917-88408c80-f7be-11ea-9d22-a5b9da5f125a.png)

**Comment by JunTaoLuo** [comment]
Odd, I just upgraded to Preview 3.0 and I'm able to work in VS. I also tried a fresh clone and it seems to work. Everything seems to work on my machine so I'm not sure what's going on. 

From what you described I wonder if there's an issue with packages that were restored. Maybe try clearing your obj/bin folders and see if that makes a difference?

**Comment by tebeco** [comment]
Attempted multiple `git clean -fdx` + `git reset --hard` and changed to `master`
that's weird

**Comment by tebeco** [comment]
I think something is broken in my box but I can't understand why it would affect only `tye` yet
I can't even repair RC1 ... error is very very weird

**Comment by tebeco** [comment]
Changing `TargetFramework` from `net5.0` to `netcoreapp3.1` seems to have fixed `Microsoft.Tye.Core` but break again when I change it back to `net5.0`
I really think VS2019 is just completly broken sicne RC1 update

**Comment by tebeco** [comment]
uninstalled all SDK / VS / InstallCleanup / reinstall VS2019 from scratch
same issue
TBH this might be a big show stopper for me
This is the only repo that seems to be affected and I'm not sure yet how

If you have any contact on the VS team whilling to do a live call to pin down the issue .... I'll take the opportunity

**Comment by tebeco** [comment]
maybe @terrajobst has some info on that

ok so ...
here is what happen when I run from the CLI :
`restore.cmd` and `build.cmd` are using `DOTNET_ROOT` that is supposed to point to `./.dotnet` which is driven by `dotnet/arcade` which for this repo is supposed to be `preview6

![image](https://user-images.githubusercontent.com/2266487/93343343-acd54c80-f830-11ea-94e1-44c2b4a6a4cc.png)
![image](https://user-images.githubusercontent.com/2266487/93343122-6b44a180-f830-11ea-9d33-5944afac24bd.png)


Now let's open Visual Studio
![image](https://user-images.githubusercontent.com/2266487/93343530-e4dc8f80-f830-11ea-97fd-01f5bb5caecf.png)

What is going on here ???

**Comment by tebeco** [comment]
@JunTaoLuo can you confirm me that this was already disabled for you ?

I had to disable this :
![image](https://user-images.githubusercontent.com/2266487/93358531-e4002980-f841-11ea-988c-c709dfced9b9.png)

and then VS is not mutating these files anymore
I think there's possibly a bug  in VS is it can't find it own generated `targets`

**Comment by JunTaoLuo** [comment]
Ah yes, I have disabled that option. FYI, I found some issues in the SDK that mentions some of the symptoms here: https://github.com/dotnet/sdk/issues/13179 and https://github.com/dotnet/sdk/issues/13614. However, those are specific to WPF apps which this is not so I'm not sure if they are relevant. @dsplaisted would you be able to help here?

**Comment by tebeco** [comment]
I wonder if updating the SDK used by the current repo to at least RC1 it might help

but i'm not sure how to do so with arcade

bonus:
Rx has issue since preview6 and i think i saw a reference to Rx in a project

**Comment by JunTaoLuo** [comment]
I was just about to reply, but yea I tried rc1 SDK which we use in other repos and it fixed the problem it seems.

**Comment by tebeco** [comment]
this would confirm the "non retro compatible behavior" regression from Preview3

preview3 installer "rc1 sdk by vs"
I believe VS uses that RC1 to generate project.assets.json

and it uses the one from global.json to "read" it

I also suppose that there was some sort of breaking change in that `targets` json output

the result is the impossibility for vs to process the file

**Comment by JunTaoLuo** [comment]
Makes sense, I didn't know we were behind on the SDK version in this repo.

**Comment by tebeco** [comment]
beware about that RX issue with WinRT changes

You might want to recheck that the code of this repo using Rx still runs

**Comment by tebeco** [comment]
closing I suppose since not linked to tye
