### ISSUE TITLE
Create a channel for dotnet/tye on Discord DotNetEvolution

### ISSUE THREAD

**Issue by tebeco** [dotnet/tye#661]
### What should we add or change to make your life better?
is there any chance to see a `tye` channel on `DotNetEvolution` Discord ?
quote from gitter:
> The fancy URL for the new discord is https://aka.ms/dotnet-discord

### Why is this important to you?
Sometimes I have the feeling that asking a question might not be asked on github or some question about an ongoing review
I'm not sure it's actually possible, just curious
eg: there's an `#AspNet` channel but I'm not sure it's being used

**Comment by cecilphillip** [comment]
ping @migueldeicaza

**Comment by tebeco** [comment]
Done ;)
![image](https://user-images.githubusercontent.com/2266487/94341445-99cd3400-0009-11eb-92d5-71cb437acc1a.png)
