### ISSUE TITLE
tye watch run does not monitor cshtml files

### ISSUE THREAD

**Issue by timheuer** [dotnet/tye#666]
### Describe the bug
Watch is not monitoring cshtml files

### To Reproduce
1. Use the tutorial to get to the frontend/backend
2. Run `tye run --watch`
3. Change index.cshtml
EXPECT:
see change
ACTUAL:
no change

Changes occur in the .cs file but not in cshtml.

tye --version: 0.4.0-alpha.20371.1+d7623120d66b85bfeda8ab69eb5ff792df6b7243

**Comment by jt-pt-dev** [comment]
Still seeing this behaviour in net5.0 and 0.5.0-alpha.20555.1+fae47325b0c8d7dafcdec5d1248191b24b2adc23.

Changes to *.cs files are picked up.

Changes to *.cshtml files are not.

Was working as expected on netcoreapp3.1 and tye 0.4.0

**Comment by hossambarakat** [comment]
I have faced the same issue with version `0.5.0-alpha.20555.1+fae47325b0c8d7dafcdec5d1248191b24b2adc23`. I have raised [a pull request ](https://github.com/dotnet/tye/pull/831) to resolve this issue.
