### ISSUE TITLE
tye run works, tye build and deploy fail

### ISSUE THREAD

**Issue by codeputer** [dotnet/tye#680]
### Describe the bug
Worked through the tutorial, and got everything working fine using "Tye run" - which worked great Then, when I tried to deploy to my docker hub, and local k8s, I was not able to get that working with a failed TFM .net5.0.

### To Reproduce

I ran the tye build -v debug, and got the following log file which gave build errors.  I could not resolve these.

### Further technical details
Tried to provide the Nuget files via the MSBUILD_NUGET_PATH="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json;https://api.nuget.org/v3/index.json"
but no difference in output

- Include the output of `tye --version`
0.2.0-alpha.20258.3+bf3bc0913b37e77f5f3ef14f409b3feb794cc447
and then 
0.4.0-alpha.20371.1+d7623120d66b85bfeda8ab69eb5ff792df6b7243
[tyeproblems_newTyeVersion.log](https://github.com/dotnet/tye/files/5289568/tyeproblems_newTyeVersion.log)

- If possible rerun the command with `-v debug` and include the output
done
- The platform (Linux/macOS/Windows)
windows
[tyeproblems.log](https://github.com/dotnet/tye/files/5289553/tyeproblems.log)

**Comment by codeputer** [comment]
duh, determine I did not update to the new version - tried again, and attached a new log.

I also added a nuget.config to the solution directory:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet5" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

**Comment by codeputer** [comment]
Can I have at least a comment, or simply closed it. I don't know what TFM Tye is currently working with. Is there documentation that I'm not aware of in terms of what TFM Tye currently supports?

**Comment by tebeco** [comment]
hello,

don't worry someone will answer you when they'll have spare time

**Comment by eiximenis** [comment]
Hi @codeputer 

I had same issue, but last alhpa version (`0.5.0-alpha.20479.2+c2b7f66aaeff2160e80e8810a86b9a2e28873858`) seems to work (my net5 version is `5.0.100-rc.1.20452.10`)

**Comment by codeputer** [comment]
closing, as I'm experiencing the same issue as #683 has documented.  I know we are early, but I feel better dialogue could be had be had around net5.0 and linked up better with the RC candidate.
