### ISSUE TITLE
Tye tries to use "core branded" docker image for .NET 5.0

### ISSUE THREAD

**Issue by eiximenis** [dotnet/tye#683]
### Describe the bug
Using `tye build` or `tye deploy` for building or deploying a .NET5 project ends with error, because tye wants to use the `mcr.microsoft.com/dotnet/core/aspnet:5.0` docker image. However .NET5 docker images are under `mcr.microsoft.com/dotnet/aspnet:5.0` (no core).

### To Reproduce
Just create any project using NET 5 and use tye build or tye deploy.

Here is `tye build -v debug` sample output:

```
Restoring and evaluating projects
Resolved metadata for service webclient at D:\dotnet2020\src\WebClient\obj\Debug\net5.0\MicrosoftTye.ProjectMetadata.txtResolved metadata for service gamemanagerservice at D:\dotnet2020\src\GameManagerService\obj\Debug\net5.0\MicrosoftTye.ProjectMetadata.txt
Resolved metadata for service statisticsservice at D:\dotnet2020\src\StatisticsService\obj\Debug\net5.0\MicrosoftTye.ProjectMetadata.txt
Restore and project evaluation took: 2679.6643ms
Found application version: 1.0.0
RunCommand=D:\dotnet2020\src\WebClient\bin\Debug\net5.0\WebClient.exe
RunArguments=
TargetPath=D:\dotnet2020\src\WebClient\bin\Debug\net5.0\WebClient.dll
PublishDir=bin\Debug\net5.0\publish\
AssemblyName=WebClient
IntermediateOutputPath=obj\Debug\net5.0\
Found target framework: net5.0
Parsed target framework name: net
Parsed target framework version: 5.0
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 4.3168ms
Found application version: 1.0.0
RunCommand=D:\dotnet2020\src\GameManagerService\bin\Debug\net5.0\GameManagerService.exe
RunArguments=
TargetPath=D:\dotnet2020\src\GameManagerService\bin\Debug\net5.0\GameManagerService.dll
PublishDir=bin\Debug\net5.0\publish\
AssemblyName=GameManagerService
IntermediateOutputPath=obj\Debug\net5.0\
Found target framework: net5.0
Parsed target framework name: net
Parsed target framework version: 5.0
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 4.1481ms
Found application version: 1.0.0
RunCommand=D:\dotnet2020\src\StatisticsService\bin\Debug\net5.0\StatisticsService.exe
RunArguments=
TargetPath=D:\dotnet2020\src\StatisticsService\bin\Debug\net5.0\StatisticsService.dll
PublishDir=bin\Debug\net5.0\publish\
AssemblyName=StatisticsService
IntermediateOutputPath=obj\Debug\net5.0\
Found target framework: net5.0
Parsed target framework name: net
Parsed target framework version: 5.0
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 2.9188ms
Processing Service 'webclient'...
    Applying container defaults...
    Done Applying container defaults...
    Compiling Services...
    Done Compiling Services...
    Publishing Project...
        Running 'dotnet publish'.
        > dotnet publish "D:\dotnet2020\src\WebClient\WebClient.csproj" -c Release -o "C:\Users\etoma\AppData\Local\Temp\i0lclsx0.rzk"
        Done running 'dotnet publish' exit code: 0
        Created Publish Output: 'C:\Users\etoma\AppData\Local\Temp\i0lclsx0.rzk'
    Done Publishing Project...
    Building Docker Image...
        Writing Dockerfile to 'C:\Users\etoma\AppData\Local\Temp\i0lclsx0.rzk\Dockerfile'.
        Done writing Dockerfile.
        Running 'docker build'.
        > docker build "C:\Users\etoma\AppData\Local\Temp\i0lclsx0.rzk" -t webclient:1.0.0 -f "C:\Users\etoma\AppData\Local\Temp\i0lclsx0.rzk\Dockerfile"
            Sending build context to Docker daemon  6.415MB

            Step 1/4 : FROM mcr.microsoft.com/dotnet/core/aspnet:5.0
            manifest for mcr.microsoft.com/dotnet/core/aspnet:5.0 not found: manifest unknown: manifest tagged by "5.0" is not found
        Done running 'docker build' exit code: 1
Drats! 'build' failed:
        'docker build' failed.
```

### Further technical details

- tye version: `0.5.0-alpha.20479.2+c2b7f66aaeff2160e80e8810a86b9a2e28873858`
- Platform: Windows 10
- Net5.0 version: `5.0.100-rc.1.20452.10`

**Comment by eiximenis** [comment]
Some updates on this :)

It seems that if a csproj folder contains a `Dockerfile` this is used in `tye build`. However the Dockerfile runs on the context of the published folder of the project, so a "standard multistep Dockerfile" do not work (because no csproj is found).

I've been able to create my docker images, using a simple Dockerfile like:

```
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

WORKDIR /app
COPY . .
ENTRYPOINT ["dotnet", "GameManagerService.dll"]
```

* The Dockerfile **must** be named `Dockerfile` in the `csproj` folder and it is picked automatically. This implies that multistage dockerfiles can't be used.
* No way to specify other Dockerfile `(dockerFile` entry of `tye.yaml` is ignored (as stated in the doc))

**Comment by bigpod98** [comment]
Hey just a question i have been battleing with this for some time and after solving this problem i have problems with wwwroot

**Comment by codeputer** [comment]
i've got the same problem now.. but I'm new to Docker and have a couple of questions:
1) the only image i have in my docker registry (local) is mcr.microsoft.com/dotnet/runtime - why create docker file with "buster-slim",

2) entry point - as there is a front end, and a back end to my solution - would this not be required for each?

Image of my debug:
![image](https://user-images.githubusercontent.com/611541/94723069-09466a80-030d-11eb-8f8f-67eaec2b5381.png)

**Comment by eiximenis** [comment]
Hi @codeputer 
I asume these questions are about my comment :)

1.  You can use tag `5.0` instead of `5.0-buster-slim`. I ended up with buster-slim because I started with a Dockerfile generated by VS which uses this base tag. If you look at https://hub.docker.com/_/microsoft-dotnet-aspnet/ (section Full Tag Listing) you'll see that tags `5.0` and `5.0-buster-slim` refers to the same underlying image.

2. If you have a frontend and a backend then you should have two netcore projects. Each netcore project have its own Dockerfile with its own entrypoing.
