### ISSUE TITLE
Q: how do replicas work in tye

### ISSUE THREAD

**Issue by tmds** [dotnet/tye#688]
Replicas mean there are multiple instances of an application running.
In Kubernetes, a 'Service' is what is used by an application which will then resolve to one of the instances.

When developing with `tye`, what will cause the difference instances to be used?
Does the `GetServiceUri` method always resolve to the same instance?

cc @davidfowl @jkotalik

**Comment by pattisapu01** [comment]
On your localhost, replicas simply creates multiple "instances" of the program. For ex, if you specify "Replicas:2", you can see 2 instances of the program in task manager on 2 different ports. you need to use an "Ingress" with route filters to load balance when resolving the URL to service replicas with more than 1 instance via "tye" service discovery. 
https://github.com/dotnet/tye/blob/master/docs/recipes/ingress.md

**Comment by davidfowl** [comment]
You don't need an ingress to route, tye automagically balances between replicas using a tcp proxy.

**Comment by pattisapu01** [comment]
Hi @davidfowl:  If service A does service resolution on service B via "tye's" service discovery, it balances calls to service B via a round robin scheme? 
On the subject of service discovery, we are also planning to use "dapr". Should we switch over to "http/grpc" calls via dapr side car for service discovery or do you recommend staying with tye for service discovery?

**Comment by davidfowl** [comment]
> If service A does service resolution on service B via "tye's" service discovery, it balances calls to service B via a round robin scheme?

Yes tye tells you the address of the proxy and the proxy knows the addresses of the instances and round robins to each of the instances. This is a tcp proxy so it's not round robin requests, it's connections (like k8s).

> On the subject of service discovery, we are also planning to use "dapr". Should we switch over to "http/grpc" calls via dapr side car for service discovery or do you recommend staying with tye for service discovery?

If you're using dapr, I'd assume you want to use their service discovery.

**Comment by tmds** [comment]
Thanks David.

**Comment by tmds** [comment]
> This is a tcp proxy

@davidfowl what process does the tcp proxying? Is there one such process per service (that has multiple replicas)? Where does this live in the source code?
