### ISSUE TITLE
Unable to run on Latest DAPR version

### ISSUE THREAD

**Issue by NitishGawde** [dotnet/tye#689]
### Describe the bug
1.) I m using DAPR 0.11.0 but tye automatically runs on 0.7.1.
2.) I don't know because of this problem or other, app and DAPR side car unable to communicate.

### To Reproduce
Running without Tye
![image](https://user-images.githubusercontent.com/65772350/95086631-59269680-073e-11eb-818e-2270138f005a.png)

With Tye
![image](https://user-images.githubusercontent.com/65772350/95086795-870bdb00-073e-11eb-9c63-efd2559ee55f.png)

### Further technical details

-Tye Version : 0.5.0-alpha.20502.1

**Comment by codeputer** [comment]
I'm wanting to get my DAPR actor project running with Tye, but I want to wait for 5.0 RC release - is there a timeline when the sample project will work properly with 5.0RC?

**Comment by NitishGawde** [comment]
@rynowak  Thanks, previously daprd.exe located on c:\dapr now it's location change to  %USERPROFILE%/.dapr/bin after running dapr init command. the new version of dapr installation does not remove the older daprd.exe that's why TYE uses the previous version of dpar.
after changing this setting TYE working perfectly fine. Thanks.

**Comment by jkotalik** [comment]
I'll look into this, should just be a fix with a full path instead of relying on it being on the path.

**Comment by codeputer** [comment]
Thanks! Not sure where I’m going wrong here – created this frontend/backend service using .net5.0 from your samples I believe

Sorry new to Docker and k8S – can’t understand why the tye RUN would work, but the tye build and deploy fail…

Hope this helps… I have to run for the afternoon, but I’d love to get this going this week!

Regards,
Richard

**Comment by codeputer** [comment]
Sorry – I ran this command just before re-trying the build, and it updated successfully…

dotnet tool update -g Microsoft.Tye --version "0.5.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json

[cid:image001.png@01D6A16C.CC38E930]

R
