### ISSUE TITLE
Unable to run on latest DAPR version.

### ISSUE THREAD

**Issue by NitishGawde** [dotnet/tye#690]
### Describe the bug
1.) I m using DAPR 0.11.0 but tye automatically runs on 0.7.1.
2.) I don't know because of this problem or other, the app, and the DAPR side car unable to communicate.

### To Reproduce
Running without Tye
![image](https://user-images.githubusercontent.com/65772350/95086631-59269680-073e-11eb-818e-2270138f005a.png)

With Tye
![image](https://user-images.githubusercontent.com/65772350/95086795-870bdb00-073e-11eb-9c63-efd2559ee55f.png)

### Further technical details

-Tye Version : 0.5.0-alpha.20502.1

**Comment by jkotalik** [comment]
To confirm, why did you end up closing this?

**Comment by NitishGawde** [comment]
@jkotalik it is duplicated.
Somehow GitHub page, not refresh after submit, so I click submit again when I check the issue list it shows me two entries, so I closed this one.

please check this:
[https://github.com/dotnet/tye/issues/689](https://github.com/dotnet/tye/issues/689)
