### ISSUE TITLE
Tye Push always labels container images "1.0.0"

### ISSUE THREAD

**Issue by neildonkin** [dotnet/tye#707]
When using Tye Push my container images are always labelled "1.0.0" in my container registry.  I have tried changing the assembly version, but this makes no difference and there doesn't appear to be any version number setting available in the tye.yaml file.

How can I change the container image label to the correct version number?

Thanks

**Comment by jongio** [comment]
You can set <Version> in csproj
```
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Version>1.0.1</Version>
  </PropertyGroup>
```

**Comment by neildonkin** [comment]
Thanks @jongio, that worked.
