### ISSUE TITLE
tye deploy --interactive does not prompt to install ingress

### ISSUE THREAD

**Issue by jongio** [dotnet/tye#728]
### Describe the bug
I want tye to deploy ingress.  I'm using:

`tye deploy --interactive`

But I'm not getting prompted.

### To Reproduce

Run tye deploy --interactive and see if you get prompted.

### Further technical details

- Include the output of `tye --version`
0.5.0-alpha.20520.1+739de2eeb94f0246f50fa4993e953abb4b0da18a
- If possible rerun the command with `-v debug` and include the output
- The platform (Linux/macOS/Windows)
WSL2

azsdke2e
azsdke2e1

**Comment by jongio** [comment]
My hunch is that it isn't prompting either because I:
1. Already have my registry in tye.yaml
1. Already have ingress on cluster

**Comment by jkotalik** [comment]
This was primarily due to tags we believe, rest of issues were resolved with allowing preserve path for ingress.
