### ISSUE TITLE
'env_file' property not beeing recognized

### ISSUE THREAD

**Issue by codeminic** [dotnet/tye#742]
### Description
When using the `env_file` property as described in the docs, tye fails to parse the it when running `tye run` and prints out the following error message:
```
Loading Application Details...
Error parsing tye.yaml: (12, 5): Unexpected key "env_file" in tye.yaml.
```

### To Reproduce
1. Save the following content as `tye.yaml`
```
name: env-test
services:
  - name: redis
    image: redis
    env_file:
      - ./config.env
```
2. Save the following content as `config.env`
```
ALLOW_EMPTY_PASSWORD=yes
```
3. Run `tye run`

Got Exceptions? Include both the message and the stack trace
```
Loading Application Details...
Error parsing tye.yaml: (12, 5): Unexpected key "env_file" in tye.yaml.
```

### Further technical details

- Version: 0.4.0-alpha.20371.1+d7623120d66b85bfeda8ab69eb5ff792df6b7243
- Rerunning with `-v debug` did not gave any additional output
- Platform: Windows

**Comment by areller** [comment]
`d7623120d66b85bfeda8ab69eb5ff792df6b7243` (commit sha) looks like a version from couple of months ago, before `env_file` was introduced. can you try with the latest version of tye?

**Comment by tebeco** [comment]
well this commit is what you get when you do `dotnet tool install -g microsoft.tye --version 0.4.*-*` 
It's clearly not recent, but I expect the majority of consumer using this one

![image](https://user-images.githubusercontent.com/2266487/97935530-22619180-1d79-11eb-9940-08bf32e48a21.png)

@codeminic do you know how to try with a nightly to check if it was not already fixed ?

**Comment by jkotalik** [comment]
@tebeco we will be releasing a new version of tye this week hopefully, so this should be fixed in a public release shortly.

@codeminic feel free to get the latest build from CI by following this: https://github.com/dotnet/tye/blob/master/docs/getting_started.md#working-with-ci-builds

**Comment by tebeco** [comment]
Don't mind me^^ 
I was just pointing that it's to be expected that this version was still used due to the lifecycle of an ongoing `alpha`

**Comment by codeminic** [comment]
@jkotalik Worked with the CI build, thx!
