### ISSUE TITLE
tye integration with dapr sample not working...

### ISSUE THREAD

**Issue by pattisapu01** [dotnet/tye#746]
I am trying to make the dapr + tye integration sample work from https://github.com/dotnet/tye/tree/master/samples/dapr and not having success.
You can see from image below that "tye" dashboard shows all services are running.
![image](https://user-images.githubusercontent.com/21227725/98025519-cb3ed980-1dd7-11eb-9504-f626628dcd3c.png)

However, when I go to "http://localhost:58821/" (where the store service is running), 'dapr' is unable to find "products" service (see image below)

![image](https://user-images.githubusercontent.com/21227725/98025871-41434080-1dd8-11eb-985e-a977c4106488.png)

Also, when I start the "dapr" dashboard on port 8080 (using the 'dapr dashboard' command), I don't see the dapr side cars  nor the "orders", "store", "products" services running.. (see image below)

![image](https://user-images.githubusercontent.com/21227725/98025986-7354a280-1dd8-11eb-9f5b-c12aac91bcb2.png)

I am running this sample with "tye run"

Thanks

**Comment by pattisapu01** [comment]
Update # 1
If I run the following commands directly for "store" and "products" projects, the 2 dapr sidecars show in dapr dashboard
**dapr run --app-id store --app-port 5002  dotnet run**
**dapr run --app-id products --app-port 5000 dotnet run**
And I see them running in dapr dashboard
![image](https://user-images.githubusercontent.com/21227725/98066493-1e8b4900-1e25-11eb-93df-2ece506e20c9.png)
BUT, going to "store (on port 5002)" still does not load and it fails with the same message (couldn't find service: products)!
![image](https://user-images.githubusercontent.com/21227725/98066530-411d6200-1e25-11eb-960d-0038bed3e71d.png)

**Comment by jkotalik** [comment]
I'm not seeing the same error locally, but I am seeing an error with this locally with the store trying to call the products with an error message. May be the same issue; going to investigate.

**Comment by pattisapu01** [comment]
The interesting things is, dapr's service discovery seems to be flaky when invoked from "tye run". The daprClient.InvokeMethodAsync() works only sometimes. Even the "Invoke" via the web url (ex: http://localhost:daprport/v1.0/Invoke/products/method/ping) also only works occasionally. When it doesn't work, I get the error, "{"errorCode":"ERR_DIRECT_INVOKE","message":"couldn't find service: products". In the logs for the dapr side process port, I see these messages.. (I added a method called "ping" with HTTPGet on the products end point)

- dapr_http_server_latency_bucket{app_id="products",method="GET",path="/v1.0/invoke/products/method/ping",status="500",le="1"} 0
- dapr_http_server_latency_bucket{app_id="products",method="GET",path="/v1.0/invoke/products/method/ping",status="500",le="2"} 0
- dapr_http_server_latency_bucket{app_id="products",method="GET",path="/v1.0/invoke/products/method/ping",status="500",le="3"} 0
- dapr_http_server_latency_bucket{app_id="products",method="GET",path="/v1.0/invoke/products/method/ping",status="500",le="4"} 0
- dapr_http_server_latency_bucket{app_id="products",method="GET",path="/v1.0/invoke/products/method/ping",status="500",le="5"} 0

**Comment by jkotalik** [comment]
@pattisapu01 I went ahead and submitted a PR for the dapr sample, which is now working locally for me. Can you confirm this works now for you?

**Comment by pattisapu01** [comment]
I am still not able to test out the "service to service" invocation @jkotalik 
I am getting the error {"errorCode":"ERR_DIRECT_INVOKE","message":"couldn't find service: orders"}
when trying to invoke HTTPGET on URL: http://localhost:62621/v1.0/invoke/orders/method/api/orders/ping  (I added a simple "ping" method on orders controller).
I re-installed dapr and tye (tye is on latest CLI version: 0.6.0-alpha.20555.2+01ec0ca7d14202fe46ab762a7784069d43f76afa), but no luck. However, when I do the same thing on a different machine, it works! 
How can I debug the dapr service invocation issues?
