### ISSUE TITLE
Evaluated project metadata file could not be found for service transactions

### ISSUE THREAD

**Issue by nickraphael** [dotnet/tye#766]
Windows 10
Was was happily running tye last week.  Then avast antivirus seemed to mess it up and I had to reinstall.  Now I'm getting this error when I do 'tye run'...

Evaluated project metadata file could not be found for service transactions

### To Reproduce
Latest version.  Tye Run

**Comment by PascalSenn** [comment]
@nickraphael  
It seems like the problem are the `/obj` files

**Comment by fergalmoran** [comment]
> @nickraphael
> It seems like the problem are the `/obj` files.
> Try to remove these folders

This worked for me 😊

**Comment by newuser** [comment]
Is it parsing for unsuccessful build exit code? Tutorial instruction has failed at this point because some error occured due environment issues.

**Comment by jkotalik** [comment]
Which version of tye are you running in this example? Do you have a full stack trace available?

**Comment by newuser** [comment]
Perhaps it is because of different system language, version was master branch.

**Comment by syska** [comment]
Getting the same issue ... 

One simple project ... 

```
# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: all
services:
- name: yyy-proxy
  project: yyy.Proxy/yyy.Proxy.csproj

```

```
tye run -v Debug
Loading Application Details...
Restoring and evaluating projects
Evaluating project failed with exit code 1:
Ouptut: MSBUILD : error MSB1008: Only one project can be specified.
Switch: Syska\.dotnet\tools\.store\microsoft.tye\0.5.0-alpha.20555.1\microsoft.tye\0.5.0-alpha.20555.1\tools\netcoreapp3.1\any\ProjectEvaluation.targets

For switch syntax, type "MSBuild -help"

Error:
Restore and project evaluation took: 326,3943ms
Drats! 'run' failed:
        Evaluated project metadata file could not be found for service yyy-proxy
```

I do wonder about the `Switch` part of the above ... 

It specified `Syska\.dotnet` ... but the real path is: `C:\Users\Mikael Syska\.dotnet\tools` ... notice the `space` in my name ... yes, it's my real name ... 

I'm using .NET 5 if it matters. Let me know if you need more details ...

**Comment by Werner-Swart-83** [comment]
Followed the getting started page, but using .net5 getting same error.

```
tye run frontend -v Debug
Loading Application Details...
Restoring and evaluating projects
Evaluating project failed with exit code 1:
Ouptut: MSBUILD : error MSB1008: Only one project can be specified.
Switch: Swart\.dotnet\tools\.store\microsoft.tye\0.5.0-alpha.20555.1\microsoft.tye\0.5.0-alpha.20555.1\tools\netcoreapp3.1\any\ProjectEvaluation.targets

For switch syntax, type "MSBuild -help"

Error:
Restore and project evaluation took: 438.262ms
Drats! 'run' failed:
        Evaluated project metadata file could not be found for service frontend
```

**Comment by jongio** [comment]
Probably due to space in folder name.

Can you try to create a link to the folder and then open via the link, see this for ref: https://blog.jongallant.com/2020/01/onedrive-rename-remove-spaces-from-folder-name/

This will allow you to test using a path that doesn't have spaces, so we can determine that this is a Tye doesn't support paths with spaces in it issue or not.

**Comment by Werner-Swart-83** [comment]
@jongio Thank that worked.

I installed Tye using using the following command: `dotnet tool install --version "0.5.0-alpha.20555.1" --tool-path c:\dotnet-tools Microsoft.Tye`

Than ran it from that location and it worked.

```
c:\dotnet-tools\tye run frontend -v Debug
Loading Application Details...
Restoring and evaluating projects
Resolved metadata for service frontend at D:\repos\tye\frontend\obj\Debug\net5.0\MicrosoftTye.ProjectMetadata.txt
Restore and project evaluation took: 1673.1641ms
Found application version: 1.0.0
RunCommand=D:\repos\tye\frontend\bin\Debug\net5.0\frontend.exe
RunArguments=
TargetPath=D:\repos\tye\frontend\bin\Debug\net5.0\frontend.dll
PublishDir=bin\Debug\net5.0\publish\
AssemblyName=frontend
IntermediateOutputPath=obj\Debug\net5.0\
Found target framework: net5.0
Parsed target framework name: net
Parsed target framework version: 5.0
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 9.6348ms
Launching Tye Host...

[18:21:43 INF] Executing application from D:\repos\tye\frontend\frontend.csproj
[18:21:43 INF] Dashboard running on http://127.0.0.1:8000
[18:21:43 INF] Building projects
[18:21:45 INF] Launching service frontend_fda9193e-7: D:\repos\tye\frontend\bin\Debug\net5.0\frontend.exe
[18:21:46 INF] frontend_fda9193e-7 running on process id 3404 bound to http://localhost:58159, https://localhost:58160
[18:21:46 INF] Replica frontend_fda9193e-7 is moving to a ready state
[18:21:46 INF] Selected process 3404.
[18:21:46 INF] Listening for event pipe events for frontend_fda9193e-7 on process id 3404
```

**Comment by jongio** [comment]
Can you see if you can repro with CI build? 
https://github.com/dotnet/tye/blob/master/docs/getting_started.md#working-with-ci-builds

If you can, can you open a diff issue for the space in path issue?

**Comment by abhisheksiddhu** [comment]
@jongio I also faced the same issue and the workaround that @Werner-Swart-83 suggested worked. I guess the issue is not related to our project path having space but rather the install location of the tool tye having spaces.

When I run it from the default location of `%UserProfile%/.dotnet/tools` which translates 
to `C:\Users\Abhishek Siddhu\.dotnet\tools` in my case it doesn't work but when I run it from an 
artificially provided location `c:\dotnet-tools` it works

**Comment by davidda** [comment]
I encountered this error message as well when first using tye with a few newly checked out projects. The solution was simply to build the projects manually in VS once.

Perhaps this "project metadata file" is generated by the build but building the project is a later step in tye's pipeline.
