### ISSUE TITLE
binding protocol is always tcp even if i  set udp 

### ISSUE THREAD

**Issue by rmznkm** [dotnet/tye#839]
### Describe the bug

When i wanna port forward for 6831/upd it forward 6831/tcp 
 - name: jaeger
    image: jaegertracing/all-in-one:latest
    bindings:
      - name: "udp" 
        port: "6831"
        protocol: Udp
      - name: "tcp"
        port: "16686"

### To Reproduce
 - name: jaeger
    image: jaegertracing/all-in-one:latest
    bindings:
      - name: "udp" 
        port: "6831"
        protocol: Udp
      - name: "tcp"
        port: "16686"

### Further technical details
4af6aeaafed5        jaegertracing/all-in-one:latest            "/go/bin/all-in-one-…"   2 minutes ago       Up 2 minutes        5775/udp, 5778/tcp, 14250/tcp, **0.0.0.0:6831->6831/tcp**, 6831-6832/udp, 14268/tcp, 0.0.0.0:16686->16686/tcp     jaeger_3ea1d146-3

 tye --version
0.5.0-alpha.20555.1+fae47325b0c8d7dafcdec5d1248191b24b2adc23

- If possible rerun the command with `-v debug` and include the output
windows docker dekstop

**Comment by jooooel** [comment]
👍 Reported the same thing here https://github.com/dotnet/tye/issues/658
