### ISSUE TITLE
'Tye' does not exist in the namespace 'Microsoft'

### ISSUE THREAD

**Issue by eliassal** [dotnet/tye#856]
I am reading an article https://www.codemag.com/Article/2010052/Project-Tye-Creating-Microservices-in-a-.NET-Way and trying to run the app using 
`tye run --dashboard or dotnet build`

 but getting stuck with the error 

```
PS C:\Projects\CodeMag\projectTye\frontend> dotnet build
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
C:\CodeMag\projectTye\frontend\Startup.cs(11,17): error CS0234: The type or namespace name 'Tye' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\CodeMag\projectTye\frontend\frontend.csproj]
```

I did before 
`dotnet add package Microsoft.Tye.Extensions.Configuration --version 0.5.0-alpha.20555.1`
and can see in the csprj file

```
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Tye.Extensions.Configuration" Version="0.5.0-alpha.20555.1" />
  </ItemGroup>
```

And of course I added to startup.cs
```
using Microsoft.Tye;
using Microsoft.Tye.Extensions.Configuration;
```
Do I need anything else?

**Comment by jkotalik** [comment]
You shouldn't need to have `using Microsoft.Tye;` in your startup file.

**Comment by eliassal** [comment]
Yes correct, I did and no building error anymore

**Comment by maacpiash** [comment]
I'm facing this same issue. I've installed `Microsoft.Tye.Extensions.Configuration` version `0.6.0-alpha.21070.5` in a `blazorserver` project.
