### ISSUE TITLE
Be able to NOT strip away path prefix with ingress

### ISSUE THREAD

**Issue by andreakn** [dotnet/tye#865]
### What should we add or change to make your life better?
for using ingress:
Have an option to *not* trim the path prefix when using ingress. Ideally this would be a per-service - setting

### Why is this important to you?
I am trying to create an OIDC-sidecar for my web-applications. however the paths don't line up properly when using Microsoft.AspNetCore.Authentication.OpenIdConnect.

**Comment by jkotalik** [comment]
You can use the element `preservePath` which is part of an ingress binding to not trim the start of the path. We added it to the json schema but forgot to add it to the documentation. I'll add that quickly now.
