### ISSUE TITLE
Can we use tye to deploy a project without containers or k8s?

### ISSUE THREAD

**Issue by gainorloss** [dotnet/tye#887]
### Why is this important to you?
because we are using micro-services without containers and k8s in our current level.

**Comment by jkotalik** [comment]
Please reopen if you have more information, but there isn't anything actionable here.

**Comment by jkotalik** [comment]
I see the title now, similar to:
https://github.com/dotnet/tye/issues/854
https://github.com/dotnet/tye/issues/494
https://github.com/dotnet/tye/issues/731
https://github.com/dotnet/tye/issues/727

**Comment by gainorloss** [comment]
Even we have no azure 、service fabric、docker ,k8s and other any containers technology ,we develop and deploy inital project and   
build or publish to our aliyun server by using jenkins ,so tye can simplify out integration? Now we know about tye from net conf, only use it to run some project and observe the tye dashboard , the run command can run without any other containers , deploy or build can ?My personal idea! forgive me.

**Comment by jkotalik** [comment]
It is still unlikely for us to support any arbitrary deployment location. Potentially we could make an extensibility model for tye deployments.

**Comment by gainorloss** [comment]
Now can we have a solution?Or we should think about this.

**Comment by jkotalik** [comment]
I don't think we are going to build a solution that publishes directly to a different location. Maybe at some point we add a solution which calls dotnet publish on each project and provides a location to each.

**Comment by gainorloss** [comment]
> It is still unlikely for us to support any arbitrary deployment location. Potentially we could make an extensibility model for tye deployments.

I'm so sorry that  i just want to know what'is your meaning. 


> Now can we have a solution?Or we should think about this.

The solution is not the VS solution(.sln),i just want to know your meaning.(Sorry, my english is poor,i couldn't transimit my meaning correctly.)
