### ISSUE TITLE
Support doing `tye run` with release assets.

### ISSUE THREAD

**Issue by jkotalik** [dotnet/tye#90]
Right now, there are some hard coded places where we assume we are building and using debug assets in `tye run`. People may want to do `tye run` with release bits. This could come from a flag passed into `tye run`.

**Comment by rynowak** [comment]
We updated the logic so that it's not hardcoded, but we still don't have a way for users to say they want to run in release mode.

**Comment by rynowak** [comment]
Looks like #383 will address this.
