### ISSUE TITLE
Backend project name with "." in middle (eg: Social.API) throwing error in tye run

### ISSUE THREAD

**Issue by MayankRSI** [dotnet/tye#903]
**Describe the bug**
Backend project name with "." in middle (eg: Social.API) throwing error in tye run

**To Reproduce:**
add backend project with name **Social.API** and run tye command

**Error Details**
An unhandled exception occurred while processing the request.
InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)

Stack Query Cookies Headers Routing
InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
System.Net.Http.HttpClient.GetAsync(string requestUri)
SocialWeb.WeatherClient.GetWeatherAsync() in WeatherClient.cs
+
            var responseMessage = await this.client.GetAsync("/api/weatherforecast");
SocialWeb.Pages.IndexModel.OnGet(WeatherClient client) in Index.cshtml.cs
+
            Forecasts = await client.GetWeatherAsync();
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+NonGenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details

**Comment by Phiph** [comment]
Hey Mayank,

I've got projects with a . in the middle too and it works fine. 

Can you share with us the Tye commands you're using? 

It may also be worth trying to run tye init to get a YAML file.

**Comment by MayankRSI** [comment]
I Follow the below article
https://github.com/dotnet/tye/blob/master/docs/tutorials/hello-tye/00_run_locally.md

**below are the commands:**
mkdir SocialDemo
cd SocialDemo
dotnet new razor -n Social.Web
tye run Social.Web
dotnet new webapi -n Social.API
dotnet new sln
dotnet sln add Social.Web Social.API
tye run
Add a file WeatherForecast.cs to the Social.Web project.
dotnet add Social.Web/Social.Web.csproj package Microsoft.Tye.Extensions.Configuration  --version "0.4.0-*"

**Below is the yml file generated after tye init**

# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: socialdemo
services:
- name: social-web
  project: Social.Web/Social.Web.csproj
- name: social-api
  project: Social.API/Social.API.csproj

 I also attached the source code where i am getting the issue after running **tye run** and click on Social.Web url on tye dashboard. 
[SocialDemo.zip](https://github.com/dotnet/tye/files/5849079/SocialDemo.zip)

**Comment by MayankRSI** [comment]
now i got the issue, i change below line of code from "Social.API" to "Social-API" and it is working now.

from
                client.BaseAddress = Configuration.GetServiceUri("Social.API");
to 
                client.BaseAddress = Configuration.GetServiceUri("Social-API");

**Comment by MayankRSI** [comment]
after changing code from "Social.API" to "Social-API" it is working now.
