### ISSUE TITLE
Log total time for running tye init and tye deploy

### ISSUE THREAD

**Issue by jkotalik** [dotnet/tye#91]
Like dotnet build, printing the total runtime would be good for diagnostics.

**Comment by andresrsanchez** [comment]
Is something like this enough?

https://github.com/microsoft/msbuild/blob/2d82e1a861d890fce68c8e2d42b569e5bbaf5687/src/Build/Logging/LogFormatter.cs#L52

**Comment by jkotalik** [comment]
Yeah that seems okay. I think just outputting the total runtime in seconds/milliseconds is better though, as it matches dotnet build.

Are you interested in doing this change? Feel free to make a PR if so 😄
