### ISSUE TITLE
Check-in: Is Tye still active?

### ISSUE THREAD

**Issue by jlikens** [dotnet/tye#950]
Just checking in to see what's going on in Tye Land.  I've given some talks on it, and last I heard (in November) it was targeted as being integrated in some fashion into .NET 6.  Looking at the contrib graph, things have definitely slowed down in recent months.

Any guidance from the core team?

Thanks!

**Comment by glennc** [comment]
Hey @jlikens, we are still working on Tye and planning to move forward with it. But we had some priorities come up in other areas and things have slowed down for a bit while we take care of them. You should see some announcements and such from us again soon.
