### ISSUE TITLE
Tye service APIs are broken

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#97]
### Describe the bug

Tye service APIs are broken

### To Reproduce

Try to call `/api/v1/services` - it will throw on the server side because the types are no longer JSON serializable.

**Comment by jkotalik** [comment]
I'm not seeing that issue locally with latest master bits:
![image](https://user-images.githubusercontent.com/8302101/77108265-1dfd8980-69df-11ea-8d8e-4d118a6b919b.png)
