### ISSUE TITLE
Tye with Managed Identities

### ISSUE THREAD

**Issue by NRKirby** [dotnet/tye#988]
I have an app that uses Managed Identity to connect to Azure App Configuration. 

Is Managed Identities supported or on the roadmap?

**Comment by jongio** [comment]
Can you tell us more about your setup?  Which app host?  Tye shouldn't really need to be configured to use MI - at least I don't.  But want to hear more
https://github.com/jongio/memealyzer/tree/main/pac/net/tye

**Comment by NRKirby** [comment]
Hey @jongio, so I've got this working now. What I thought was Managed Identity related was actually to do with environment variables. All I had to do was specify them in `tye.yaml` and it worked!

FYI this (work) project in question has environment variables in `launchSettings.json`. I'm not exactly sure the reason why but our set up deploys onto linux containers in aks. 

In my case I'd love to see Tye pick up those variables when I do `tye init`
