### ISSUE TITLE
Dapr extension pub/sub error: no pubsub is configured

### ISSUE THREAD

**Issue by tonysneed** [dotnet/tye#990]
When running Type with the Dapr extension using pub/sub, I got an exception with `daprClient.PublishEventAsync("pubsub", "weather", weather)`:

```
Message=Publish operation failed: the Dapr endpoint indicated a failure.
Source=Dapr.Client
Inner Exception: RpcException: Status(StatusCode="FailedPrecondition", Detail="no pubsub is configured")
```

I do not get the exception when running **dapr** directly: `dapr run --app-id publisher -- dotnet run`

I can verify in the **Components** tab of the Dapr Dashboard that **pubsub** is configured properly.

_Originally posted by @tonysneed in https://github.com/dotnet/tye/issues/984#issuecomment-800631405_

**Comment by jkotalik** [comment]
Hm, I'm not seeing this repro locally.

What version of tye and dapr are you using?

**Comment by tonysneed** [comment]
### Versions
Tye version: `0.6.0-alpha.21070.5+a42e4463943e3136dbd1de38474d8d62b802797c`
Dapr version: `CLI version: 1.0.1` `Runtime version: 1.0.1`
OS: `macOS Big Sur 11.2.3`

### Steps to Reproduce
1. Clone the demo repo: https://github.com/tonysneed/Demo.DaprPubSub
2. From the solution root run: `tye run --debug *`.
3. Open the solution in Visual Studio (Rider on the Mac).
4. Set a breakpoint on line 30 of Worker.cs in the Publisher project: `await _daprClient.PublishEventAsync(Constants.PubSubName, "weather", weather);`
5. In Exception Settings, break on all CLR exceptions.
4. Attach the debugger to **Subscriber**.
5. Attach the debugger to **Publisher**.
6. When the breakpoint is hit, press F5 to continue.

The following exception takes place:
```
Dapr.DaprException: Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
 ---> Grpc.Core.RpcException: Status(StatusCode="FailedPrecondition", Detail="no pubsub is configured")
   at Dapr.Client.DaprClientGrpc.MakePublishRequest(String pubsubName, String topicName, ByteString content, Dictionary`2 metadata, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Dapr.Client.DaprClientGrpc.MakePublishRequest(String pubsubName, String topicName, ByteString content, Dictionary`2 metadata, CancellationToken cancellationToken)
   at Publisher.Worker.ExecuteAsync(CancellationToken stoppingToken) in /Users/anthonysneed/Source/Demo.DaprPubSub/Publisher/Worker.cs:line 30
```

I have been able to reproduce this behavior on both macOS and Windows 10.

**Comment by tonysneed** [comment]
@jkotalik Are you able to reproduce the error using the steps I provided? This is preventing me from using Tye to debug Dapr pub/sub using Visual Studio. Thanks.

**Comment by hafiz-personal** [comment]
I solved it by mounting the components folder from the host to the dapr container

**Comment by tonysneed** [comment]
@hafiz-personal Do you have a sample or snippet I could use?

**Comment by tonysneed** [comment]
I figured it out. Simply add `components-path` to the `dapr` extension section of tye.yaml.
```
extensions:
- name: dapr
  log-level: debug
  components-path: "./dapr/components"
```
This will resolve the `no pubsub is configured` error.

@jkotalik This looks like a bug in tye. It should use the default Dapr components path. @rynowak Would you agree?

**Comment by philliphoff** [comment]
Closing.  Please reopen if the current behavior is insufficient.

**Comment by iarsal7** [comment]
> I solved it by mounting the components folder from the host to the dapr container

what do you mean host ?
